// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace GameServer.Entities
{
	[Table("account_credentials")]
	public class AccountCredential
	{
		[Column("id"              , IsPrimaryKey = true )] public Guid      Id             { get; set; } // uuid
		[Column("account_id"                            )] public Guid      AccountId      { get; set; } // uuid
		[Column("provider"        , CanBeNull    = false)] public string    Provider       { get; set; } = null!; // character varying(20)
		[Column("provider_user_id", CanBeNull    = false)] public string    ProviderUserId { get; set; } = null!; // character varying(255)
		[Column("password_hash"                         )] public string?   PasswordHash   { get; set; } // text
		[Column("created_at"                            )] public DateTime? CreatedAt      { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// fk_credential_account
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(AccountId), OtherKey = nameof(Entities.Account.Id))]
		public Account Account { get; set; } = null!;
		#endregion
	}
}
