// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace GameServer.Entities
{
	[Table("account_security")]
	public class AccountSecurity
	{
		[Column("account_id"        , IsPrimaryKey = true)] public Guid  AccountId        { get; set; } // uuid
		[Column("email_verified"                         )] public bool? EmailVerified    { get; set; } // boolean
		[Column("phone_verified"                         )] public bool? PhoneVerified    { get; set; } // boolean
		[Column("two_factor_enabled"                     )] public bool? TwoFactorEnabled { get; set; } // boolean

		#region Associations
		/// <summary>
		/// fk_security_account
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(AccountId), OtherKey = nameof(Account.Id))]
		public Account Fksecurityaccount { get; set; } = null!;
		#endregion
	}
}
