// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace GameServer.Entities
{
	[Table("accounts")]
	public class Account
	{
		[Column("id"        , IsPrimaryKey = true)] public Guid      Id        { get; set; } // uuid
		[Column("created_at"                     )] public DateTime? CreatedAt { get; set; } // timestamp (6) without time zone
		[Column("last_login"                     )] public DateTime? LastLogin { get; set; } // timestamp (6) without time zone
		[Column("status"                         )] public int?      Status    { get; set; } // integer

		#region Associations
		/// <summary>
		/// fk_character_account backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Character.AccountId))]
		public IEnumerable<Character> Characters { get; set; } = null!;

		/// <summary>
		/// fk_credential_account backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AccountCredential.AccountId))]
		public IEnumerable<AccountCredential> AccountCredentials { get; set; } = null!;

		/// <summary>
		/// fk_security_account backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Entities.AccountSecurity.AccountId))]
		public AccountSecurity? AccountSecurity { get; set; }
		#endregion
	}
}
