// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace GameServer.Entities
{
	[Table("breakthrough_conditions")]
	public class BreakthroughCondition
	{
		[Column("id"            , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     Id            { get; set; } // integer
		[Column("realm_id"                                                                                        )] public int     RealmId       { get; set; } // integer
		[Column("condition_type"                                                                                  )] public string? ConditionType { get; set; } // character varying(50)
		[Column("target_id"                                                                                       )] public int?    TargetId      { get; set; } // integer
		[Column("success_bonus"                                                                                   )] public double? SuccessBonus  { get; set; } // double precision
		[Column("max_stack"                                                                                       )] public int?    MaxStack      { get; set; } // integer

		#region Associations
		/// <summary>
		/// fk_condition_realm
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(RealmId), OtherKey = nameof(RealmTemplate.Id))]
		public RealmTemplate Realm { get; set; } = null!;
		#endregion
	}
}
