// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace GameServer.Entities
{
	[Table("breakthrough_attempts")]
	public class BreakthroughAttempt
	{
		[Column("id"          , IsPrimaryKey = true)] public Guid      Id          { get; set; } // uuid
		[Column("character_id"                     )] public Guid?     CharacterId { get; set; } // uuid
		[Column("realm_id"                         )] public int?      RealmId     { get; set; } // integer
		[Column("success_rate"                     )] public double?   SuccessRate { get; set; } // double precision
		[Column("result"                           )] public bool?     Result      { get; set; } // boolean
		[Column("created_at"                       )] public DateTime? CreatedAt   { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// fk_attempt_character
		/// </summary>
		[Association(ThisKey = nameof(CharacterId), OtherKey = nameof(Entities.Character.Id))]
		public Character? Character { get; set; }
		#endregion
	}
}
