// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace GameServer.Entities
{
	[Table("character_stats")]
	public class CharacterStat
	{
		[Column("character_id"   , IsPrimaryKey = true)] public Guid    CharacterId    { get; set; } // uuid
		[Column("realm_id"                            )] public int?    RealmId        { get; set; } // integer
		[Column("cultivation"                         )] public long?   Cultivation    { get; set; } // bigint
		[Column("hp"                                  )] public int?    Hp             { get; set; } // integer
		[Column("mp"                                  )] public int?    Mp             { get; set; } // integer
		[Column("physique"                            )] public int?    Physique       { get; set; } // integer
		[Column("attack"                              )] public int?    Attack         { get; set; } // integer
		[Column("speed"                               )] public int?    Speed          { get; set; } // integer
		[Column("spiritual_sense"                     )] public int?    SpiritualSense { get; set; } // integer
		[Column("fortune"                             )] public double? Fortune        { get; set; } // double precision
		[Column("potential"                           )] public int?    Potential      { get; set; } // integer

		#region Associations
		/// <summary>
		/// fk_stats_character
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(CharacterId), OtherKey = nameof(Character.Id))]
		public Character Fkstatscharacter { get; set; } = null!;
		#endregion
	}
}
