// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace GameServer.Entities
{
	[Table("character_current_state")]
	public class CharacterCurrentState
	{
		[Column("character_id"  , IsPrimaryKey = true)] public Guid     CharacterId   { get; set; } // uuid
		[Column("current_hp"                        )] public int      CurrentHp     { get; set; } // integer
		[Column("current_mp"                        )] public int      CurrentMp     { get; set; } // integer
		[Column("current_map_id"                    )] public int?     CurrentMapId  { get; set; } // integer
		[Column("current_pos_x"                     )] public float    CurrentPosX   { get; set; } // real
		[Column("current_pos_y"                     )] public float    CurrentPosY   { get; set; } // real
		[Column("is_dead"                           )] public bool     IsDead        { get; set; } // boolean
		[Column("current_state"                     )] public int      CurrentState  { get; set; } // integer
		[Column("last_saved_at"                     )] public DateTime LastSavedAt   { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// fk_character_current_state_character
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(CharacterId), OtherKey = nameof(Character.Id))]
		public Character Character { get; set; } = null!;
		#endregion
	}
}
