// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace GameServer.Entities
{
	[Table("characters")]
	public class Character
	{
		[Column("id"        , IsPrimaryKey = true )] public Guid      Id        { get; set; } // uuid
		[Column("account_id"                      )] public Guid      AccountId { get; set; } // uuid
		[Column("server_id"                       )] public int       ServerId  { get; set; } // integer
		[Column("name"      , CanBeNull    = false)] public string    Name      { get; set; } = null!; // character varying(50)
		[Column("model_id"                        )] public int?      ModelId   { get; set; } // integer
		[Column("gender"                          )] public int?      Gender    { get; set; } // integer
		[Column("hair_color"                      )] public int?      HairColor { get; set; } // integer
		[Column("eye_color"                       )] public int?      EyeColor  { get; set; } // integer
		[Column("face_id"                         )] public int?      FaceId    { get; set; } // integer
		[Column("created_at"                      )] public DateTime? CreatedAt { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// fk_attempt_character backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(BreakthroughAttempt.CharacterId))]
		public IEnumerable<BreakthroughAttempt> BreakthroughAttempts { get; set; } = null!;

		/// <summary>
		/// fk_character_account
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(AccountId), OtherKey = nameof(Entities.Account.Id))]
		public Account Account { get; set; } = null!;

		/// <summary>
		/// fk_character_server
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(ServerId), OtherKey = nameof(Entities.Server.Id))]
		public Server Server { get; set; } = null!;

		/// <summary>
		/// fk_character_base_stats_character backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(CharacterBaseStat.CharacterId))]
		public CharacterBaseStat? CharacterBaseStats { get; set; }

		/// <summary>
		/// fk_character_current_state_character backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(CharacterCurrentState.CharacterId))]
		public CharacterCurrentState? CharacterCurrentState { get; set; }
		#endregion
	}
}
