// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace GameServer.Entities
{
    [Table("character_current_state")]
    public class CharacterCurrentState
    {
        [Column("character_id", IsPrimaryKey = true)] public Guid CharacterId { get; set; }
        [Column("current_hp")] public int CurrentHp { get; set; }
        [Column("current_mp")] public int CurrentMp { get; set; }
        [Column("current_stamina")] public int CurrentStamina { get; set; }
        [Column("lifespan_end_game_minute")] public long LifespanEndGameMinute { get; set; }
        [Column("current_map_id")] public int? CurrentMapId { get; set; }
        [Column("current_zone_index")] public int CurrentZoneIndex { get; set; }
        [Column("current_pos_x")] public float CurrentPosX { get; set; }
        [Column("current_pos_y")] public float CurrentPosY { get; set; }
        [Column("is_dead")] public bool IsDead { get; set; }
        [Column("current_state")] public int CurrentState { get; set; }
        [Column("cultivation_started_at_utc")] public DateTime? CultivationStartedAtUtc { get; set; }
        [Column("last_cultivation_rewarded_at_utc")] public DateTime? LastCultivationRewardedAtUtc { get; set; }
        [Column("last_saved_at")] public DateTime LastSavedAt { get; set; }

        #region Associations
        [Association(CanBeNull = false, ThisKey = nameof(CharacterId), OtherKey = nameof(Character.Id))]
        public Character Character { get; set; } = null!;
        #endregion
    }
}
