// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace GameServer.Entities
{
	[Table("character_base_stats")]
	public class CharacterBaseStat
	{
		[Column("character_id"        , IsPrimaryKey = true)] public Guid    CharacterId          { get; set; } // uuid
		[Column("realm_id"                                 )] public int?    RealmId              { get; set; } // integer
		[Column("cultivation"                              )] public long?   Cultivation          { get; set; } // bigint
		[Column("base_hp"                                  )] public int?    BaseHp               { get; set; } // integer
		[Column("base_mp"                                  )] public int?    BaseMp               { get; set; } // integer
		[Column("base_physique"                            )] public int?    BasePhysique         { get; set; } // integer
		[Column("base_attack"                              )] public int?    BaseAttack           { get; set; } // integer
		[Column("base_speed"                               )] public int?    BaseSpeed            { get; set; } // integer
		[Column("base_spiritual_sense"                     )] public int?    BaseSpiritualSense   { get; set; } // integer
		[Column("base_stamina"                             )] public int?    BaseStamina          { get; set; } // integer
		[Column("lifespan_bonus"                           )] public int?    LifespanBonus       { get; set; } // integer
		[Column("base_fortune"                             )] public double? BaseFortune          { get; set; } // double precision
		[Column("base_potential"                           )] public int?    BasePotential        { get; set; } // integer
		[Column("unallocated_potential"                    )] public int?    UnallocatedPotential { get; set; } // integer

		#region Associations
		/// <summary>
		/// fk_character_base_stats_character
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(CharacterId), OtherKey = nameof(Character.Id))]
		public Character Character { get; set; } = null!;
		#endregion
	}
}
