// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Async;
using LinqToDB.Data;
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace GameServer.Entities
{
	public partial class PhamnhanOnlineDb : DataConnection
	{
		public PhamnhanOnlineDb()
		{
			InitDataContext();
		}

		public PhamnhanOnlineDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public PhamnhanOnlineDb(DataOptions<PhamnhanOnlineDb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<AccountCredential>     AccountCredentials     => this.GetTable<AccountCredential>();
		public ITable<AccountSecurity>       AccountSecurities      => this.GetTable<AccountSecurity>();
		public ITable<Account>               Accounts               => this.GetTable<Account>();
		public ITable<BreakthroughAttempt>   BreakthroughAttempts   => this.GetTable<BreakthroughAttempt>();
		public ITable<BreakthroughCondition> BreakthroughConditions => this.GetTable<BreakthroughCondition>();
		public ITable<CharacterBaseStat>     CharacterBaseStats     => this.GetTable<CharacterBaseStat>();
		public ITable<CharacterCurrentState> CharacterCurrentStates => this.GetTable<CharacterCurrentState>();
		public ITable<Character>             Characters             => this.GetTable<Character>();
		public ITable<GameTimeState>         GameTimeStates         => this.GetTable<GameTimeState>();
		public ITable<MapTemplateAdjacentMapEntity> MapTemplateAdjacentMaps => this.GetTable<MapTemplateAdjacentMapEntity>();
		public ITable<MapTemplateEntity>     MapTemplates           => this.GetTable<MapTemplateEntity>();
		public ITable<RealmTemplate>         RealmTemplates         => this.GetTable<RealmTemplate>();
		public ITable<Server>                Servers                => this.GetTable<Server>();
	}

	public static partial class ExtensionMethods
	{
		#region Table Extensions
		public static AccountCredential? Find(this ITable<AccountCredential> table, Guid id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<AccountCredential?> FindAsync(this ITable<AccountCredential> table, Guid id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}

		public static AccountSecurity? Find(this ITable<AccountSecurity> table, Guid accountId)
		{
			return table.FirstOrDefault(e => e.AccountId == accountId);
		}

		public static Task<AccountSecurity?> FindAsync(this ITable<AccountSecurity> table, Guid accountId, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.AccountId == accountId, cancellationToken);
		}

		public static Account? Find(this ITable<Account> table, Guid id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<Account?> FindAsync(this ITable<Account> table, Guid id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}

		public static BreakthroughAttempt? Find(this ITable<BreakthroughAttempt> table, Guid id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<BreakthroughAttempt?> FindAsync(this ITable<BreakthroughAttempt> table, Guid id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}

		public static BreakthroughCondition? Find(this ITable<BreakthroughCondition> table, int id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<BreakthroughCondition?> FindAsync(this ITable<BreakthroughCondition> table, int id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}

		public static CharacterBaseStat? Find(this ITable<CharacterBaseStat> table, Guid characterId)
		{
			return table.FirstOrDefault(e => e.CharacterId == characterId);
		}

		public static Task<CharacterBaseStat?> FindAsync(this ITable<CharacterBaseStat> table, Guid characterId, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.CharacterId == characterId, cancellationToken);
		}

		public static CharacterCurrentState? Find(this ITable<CharacterCurrentState> table, Guid characterId)
		{
			return table.FirstOrDefault(e => e.CharacterId == characterId);
		}

		public static Task<CharacterCurrentState?> FindAsync(this ITable<CharacterCurrentState> table, Guid characterId, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.CharacterId == characterId, cancellationToken);
		}

		public static Character? Find(this ITable<Character> table, Guid id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<Character?> FindAsync(this ITable<Character> table, Guid id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}

		public static GameTimeState? Find(this ITable<GameTimeState> table, int id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<GameTimeState?> FindAsync(this ITable<GameTimeState> table, int id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}

		public static RealmTemplate? Find(this ITable<RealmTemplate> table, int id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<RealmTemplate?> FindAsync(this ITable<RealmTemplate> table, int id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}

		public static Server? Find(this ITable<Server> table, int id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<Server?> FindAsync(this ITable<Server> table, int id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}
		#endregion
	}
}

