// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace GameServer.Entities
{
	[Table("realm_templates")]
	public class RealmTemplate
	{
		[Column("id"                    , IsPrimaryKey = true)] public int       Id                   { get; set; } // integer
		[Column("name"                                       )] public string?   Name                 { get; set; } // character varying(50)
		[Column("stage_name"                                 )] public string?   StageName            { get; set; } // character varying(50)
		[Column("max_cultivation"                            )] public long?     MaxCultivation       { get; set; } // bigint
		[Column("lifespan"                                   )] public int       Lifespan             { get; set; } // integer
		[Column("base_breakthrough_rate"                     )] public double?   BaseBreakthroughRate { get; set; } // double precision
		[Column("failure_penalty"                            )] public double?   FailurePenalty       { get; set; } // double precision
		[Column("created_at"                                 )] public DateTime? CreatedAt            { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// fk_condition_realm backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(BreakthroughCondition.RealmId))]
		public IEnumerable<BreakthroughCondition> BreakthroughConditions { get; set; } = null!;
		#endregion
	}
}
