// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace GameServer.Entities
{
	[Table("servers")]
	public class Server
	{
		[Column("id"    , IsPrimaryKey = true)] public int     Id     { get; set; } // integer
		[Column("name"                       )] public string? Name   { get; set; } // character varying(50)
		[Column("status"                     )] public int?    Status { get; set; } // integer

		#region Associations
		/// <summary>
		/// fk_character_server backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Character.ServerId))]
		public IEnumerable<Character> Characters { get; set; } = null!;
		#endregion
	}
}
