BEGIN;

ALTER TABLE public.character_base_stats
    DROP COLUMN IF EXISTS base_physique,
    DROP COLUMN IF EXISTS bonus_physique,
    DROP COLUMN IF EXISTS physique_upgrade_count,
    ADD COLUMN IF NOT EXISTS base_move_speed numeric(10,4) NOT NULL DEFAULT 100.0,
    ADD COLUMN IF NOT EXISTS unallocated_potential integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cultivation_progress numeric(18,6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS hp_upgrade_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS mp_upgrade_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS attack_upgrade_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS speed_upgrade_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS spiritual_sense_upgrade_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fortune_upgrade_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS active_martial_art_id integer NULL,
    ADD COLUMN IF NOT EXISTS potential_reward_locked boolean NOT NULL DEFAULT false;

UPDATE public.character_base_stats
SET
    base_move_speed = COALESCE(base_move_speed, 100.0),
    unallocated_potential = COALESCE(unallocated_potential, COALESCE(base_potential, 0)),
    cultivation_progress = COALESCE(cultivation_progress, 0),
    potential_reward_locked = COALESCE(potential_reward_locked, false);

ALTER TABLE public.character_current_state
    ADD COLUMN IF NOT EXISTS cultivation_started_at_utc timestamp without time zone NULL,
    ADD COLUMN IF NOT EXISTS last_cultivation_rewarded_at_utc timestamp without time zone NULL;

CREATE TABLE IF NOT EXISTS public.spiritual_energy_templates (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    lk_per_minute numeric(10,4) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT spiritual_energy_templates_pkey PRIMARY KEY (id),
    CONSTRAINT spiritual_energy_templates_code_key UNIQUE (code)
);

DROP TABLE IF EXISTS public.potential_stat_templates;

CREATE TABLE IF NOT EXISTS public.potential_stat_upgrade_tiers (
    target_stat integer NOT NULL,
    tier_index integer NOT NULL,
    max_upgrade_count integer NOT NULL,
    potential_cost_per_upgrade integer NOT NULL,
    stat_gain_per_upgrade numeric(18,6) NOT NULL,
    is_enabled boolean NOT NULL DEFAULT true,
    CONSTRAINT potential_stat_upgrade_tiers_pkey PRIMARY KEY (target_stat, tier_index)
);

ALTER TABLE public.realm_templates
    ADD COLUMN IF NOT EXISTS absorption_multiplier numeric(10,4) NOT NULL DEFAULT 1.0;

ALTER TABLE public.map_templates
    ADD COLUMN IF NOT EXISTS spiritual_energy numeric(10,4) NOT NULL DEFAULT 100,
    ADD COLUMN IF NOT EXISTS supports_cave_placement boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.map_zone_slots (
    id integer NOT NULL,
    map_template_id integer NOT NULL,
    zone_index integer NOT NULL,
    spiritual_energy_template_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT map_zone_slots_pkey PRIMARY KEY (id),
    CONSTRAINT map_zone_slots_map_template_zone_key UNIQUE (map_template_id, zone_index),
    CONSTRAINT fk_map_zone_slots_map_template
        FOREIGN KEY (map_template_id) REFERENCES public.map_templates(id),
    CONSTRAINT fk_map_zone_slots_spiritual_energy
        FOREIGN KEY (spiritual_energy_template_id) REFERENCES public.spiritual_energy_templates(id)
);

CREATE TABLE IF NOT EXISTS public.map_spawn_points (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_template_id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    spawn_category integer NOT NULL DEFAULT 4,
    pos_x real NOT NULL,
    pos_y real NOT NULL,
    facing_degrees real NULL,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT map_spawn_points_map_code_key UNIQUE (map_template_id, code),
    CONSTRAINT map_spawn_points_map_id_id_key UNIQUE (map_template_id, id),
    CONSTRAINT fk_map_spawn_points_map
        FOREIGN KEY (map_template_id) REFERENCES public.map_templates(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_map_spawn_points_map_template_id
    ON public.map_spawn_points (map_template_id);

CREATE TABLE IF NOT EXISTS public.map_portals (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_map_template_id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    source_x real NOT NULL,
    source_y real NOT NULL,
    interaction_radius real NOT NULL DEFAULT 24,
    interaction_mode integer NOT NULL DEFAULT 1,
    target_map_template_id integer NOT NULL,
    target_spawn_point_id integer NOT NULL,
    is_enabled boolean NOT NULL DEFAULT true,
    order_index integer NOT NULL DEFAULT 0,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT map_portals_source_code_key UNIQUE (source_map_template_id, code),
    CONSTRAINT fk_map_portals_source_map
        FOREIGN KEY (source_map_template_id) REFERENCES public.map_templates(id) ON DELETE CASCADE,
    CONSTRAINT fk_map_portals_target_map
        FOREIGN KEY (target_map_template_id) REFERENCES public.map_templates(id) ON DELETE RESTRICT,
    CONSTRAINT fk_map_portals_target_spawn
        FOREIGN KEY (target_map_template_id, target_spawn_point_id)
            REFERENCES public.map_spawn_points(map_template_id, id)
            ON DELETE RESTRICT,
    CONSTRAINT ck_map_portals_interaction_radius_positive
        CHECK (interaction_radius > 0),
    CONSTRAINT ck_map_portals_interaction_mode_valid
        CHECK (interaction_mode in (1, 2))
);

CREATE INDEX IF NOT EXISTS idx_map_portals_source_map_template_id
    ON public.map_portals (source_map_template_id);

CREATE INDEX IF NOT EXISTS idx_map_portals_target_map_template_id
    ON public.map_portals (target_map_template_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_map_templates_spiritual_energy'
    ) THEN
        ALTER TABLE public.map_templates
            ADD CONSTRAINT fk_map_templates_spiritual_energy
            FOREIGN KEY (spiritual_energy_template_id) REFERENCES public.spiritual_energy_templates(id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.game_random_tables (
    id integer NOT NULL,
    table_id character varying(100) NOT NULL,
    mode integer NOT NULL DEFAULT 0,
    fortune_enabled boolean NOT NULL DEFAULT false,
    fortune_bonus_parts_per_million_per_fortune_point integer NOT NULL DEFAULT 0,
    fortune_max_bonus_parts_per_million integer NOT NULL DEFAULT 0,
    none_entry_id character varying(100) NOT NULL DEFAULT '__none__',
    description text NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT game_random_tables_pkey PRIMARY KEY (id),
    CONSTRAINT game_random_tables_table_id_key UNIQUE (table_id)
);

CREATE TABLE IF NOT EXISTS public.game_random_entries (
    id integer NOT NULL,
    game_random_table_id integer NOT NULL,
    entry_id character varying(100) NOT NULL,
    chance_parts_per_million integer NOT NULL,
    is_none boolean NOT NULL DEFAULT false,
    order_index integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT game_random_entries_pkey PRIMARY KEY (id),
    CONSTRAINT game_random_entries_table_entry_key UNIQUE (game_random_table_id, entry_id),
    CONSTRAINT game_random_entries_table_order_key UNIQUE (game_random_table_id, order_index),
    CONSTRAINT fk_game_random_entries_table
        FOREIGN KEY (game_random_table_id) REFERENCES public.game_random_tables(id)
);

CREATE TABLE IF NOT EXISTS public.game_random_entry_tags (
    id integer NOT NULL,
    game_random_entry_id integer NOT NULL,
    tag character varying(50) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT game_random_entry_tags_pkey PRIMARY KEY (id),
    CONSTRAINT game_random_entry_tags_entry_tag_key UNIQUE (game_random_entry_id, tag),
    CONSTRAINT fk_game_random_entry_tags_entry
        FOREIGN KEY (game_random_entry_id) REFERENCES public.game_random_entries(id)
);

CREATE TABLE IF NOT EXISTS public.game_random_fortune_tags (
    id integer NOT NULL,
    game_random_table_id integer NOT NULL,
    tag character varying(50) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT game_random_fortune_tags_pkey PRIMARY KEY (id),
    CONSTRAINT game_random_fortune_tags_table_tag_key UNIQUE (game_random_table_id, tag),
    CONSTRAINT fk_game_random_fortune_tags_table
        FOREIGN KEY (game_random_table_id) REFERENCES public.game_random_tables(id)
);

INSERT INTO public.game_random_tables (
    id,
    table_id,
    mode,
    fortune_enabled,
    fortune_bonus_parts_per_million_per_fortune_point,
    fortune_max_bonus_parts_per_million,
    none_entry_id,
    description
)
VALUES (
    1,
    'monster.drop.demo_slime',
    0,
    true,
    2500,
    150000,
    '__none__',
    'Bang random demo slime drop duoc migrate tu gameRandomConfig.json'
)
ON CONFLICT (id) DO UPDATE
SET
    table_id = EXCLUDED.table_id,
    mode = EXCLUDED.mode,
    fortune_enabled = EXCLUDED.fortune_enabled,
    fortune_bonus_parts_per_million_per_fortune_point = EXCLUDED.fortune_bonus_parts_per_million_per_fortune_point,
    fortune_max_bonus_parts_per_million = EXCLUDED.fortune_max_bonus_parts_per_million,
    none_entry_id = EXCLUDED.none_entry_id,
    description = EXCLUDED.description;

INSERT INTO public.game_random_entries (
    id,
    game_random_table_id,
    entry_id,
    chance_parts_per_million,
    is_none,
    order_index
)
VALUES
    (1, 1, 'item.demo_herb', 50000, false, 1),
    (2, 1, 'currency.spirit_stone_small', 100000, false, 2)
ON CONFLICT (id) DO UPDATE
SET
    game_random_table_id = EXCLUDED.game_random_table_id,
    entry_id = EXCLUDED.entry_id,
    chance_parts_per_million = EXCLUDED.chance_parts_per_million,
    is_none = EXCLUDED.is_none,
    order_index = EXCLUDED.order_index;

INSERT INTO public.game_random_entry_tags (id, game_random_entry_id, tag)
VALUES
    (1, 1, 'item_drop'),
    (2, 2, 'currency_drop')
ON CONFLICT (id) DO UPDATE
SET
    game_random_entry_id = EXCLUDED.game_random_entry_id,
    tag = EXCLUDED.tag;

INSERT INTO public.servers (id, name, status)
VALUES (1, 'Server01', 1)
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    status = EXCLUDED.status;

INSERT INTO public.game_time_state (
    id,
    anchor_utc,
    anchor_game_minute,
    game_minutes_per_real_minute,
    days_per_game_year,
    runtime_save_interval_seconds,
    derived_state_refresh_interval_seconds
)
VALUES (
    1,
    TIMESTAMPTZ '2026-01-01 00:00:00+00',
    0,
    518400,
    360,
    2,
    5
)
ON CONFLICT (id) DO UPDATE
SET
    anchor_utc = EXCLUDED.anchor_utc,
    anchor_game_minute = EXCLUDED.anchor_game_minute,
    game_minutes_per_real_minute = EXCLUDED.game_minutes_per_real_minute,
    days_per_game_year = EXCLUDED.days_per_game_year,
    runtime_save_interval_seconds = EXCLUDED.runtime_save_interval_seconds,
    derived_state_refresh_interval_seconds = EXCLUDED.derived_state_refresh_interval_seconds;

INSERT INTO public.realm_templates (
    id,
    name,
    stage_name,
    max_cultivation,
    lifespan,
    base_breakthrough_rate,
    absorption_multiplier,
    failure_penalty
)
VALUES
    (1, 'Luyá»‡n KhÃ­ Ká»³ táº§ng 1', 'Luyá»‡n KhÃ­ Ká»³ táº§ng 1', 150, 120, 100, 0.2, 0),
    (2, 'Luyá»‡n KhÃ­ Ká»³ táº§ng 2', 'Luyá»‡n KhÃ­ Ká»³ táº§ng 2', 200, 125, 95, 0.2, 0),
    (3, 'Luyá»‡n KhÃ­ Ká»³ táº§ng 3', 'Luyá»‡n KhÃ­ Ká»³ táº§ng 3', 280, 130, 90, 0.2, 0),
    (4, 'Luyá»‡n KhÃ­ Ká»³ táº§ng 4', 'Luyá»‡n KhÃ­ Ká»³ táº§ng 4', 380, 135, 85, 0.2, 0),
    (5, 'Luyá»‡n KhÃ­ Ká»³ táº§ng 5', 'Luyá»‡n KhÃ­ Ká»³ táº§ng 5', 520, 140, 80, 0.2, 0),
    (6, 'Luyá»‡n KhÃ­ Ká»³ táº§ng 6', 'Luyá»‡n KhÃ­ Ká»³ táº§ng 6', 750, 145, 75, 0.2, 0),
    (7, 'Luyá»‡n KhÃ­ Ká»³ táº§ng 7', 'Luyá»‡n KhÃ­ Ká»³ táº§ng 7', 1200, 150, 70, 0.2, 0),
    (8, 'Luyá»‡n KhÃ­ Ká»³ táº§ng 8', 'Luyá»‡n KhÃ­ Ká»³ táº§ng 8', 1500, 155, 65, 0.2, 0),
    (9, 'Luyá»‡n KhÃ­ Ká»³ táº§ng 9', 'Luyá»‡n KhÃ­ Ká»³ táº§ng 9', 2000, 160, 40, 0.2, 0),
    (10, 'TrÃºc CÆ¡ SÆ¡ Ká»³', 'TrÃºc CÆ¡ SÆ¡ Ká»³', 5000, 180, 40, 0.3, 0),
    (11, 'TrÃºc CÆ¡ Trung Ká»³', 'TrÃºc CÆ¡ Trung Ká»³', 7000, 200, 35, 0.3, 0),
    (12, 'TrÃºc CÆ¡ Háº­u Ká»³', 'TrÃºc CÆ¡ Háº­u Ká»³', 10000, 220, 25, 0.3, 0),
    (13, 'Káº¿t Äan SÆ¡ Ká»³', 'Káº¿t Äan SÆ¡ Ká»³', 25000, 350, 30, 0.5, 0),
    (14, 'Káº¿t Äan Trung Ká»³', 'Káº¿t Äan Trung Ká»³', 35000, 400, 28, 0.5, 0),
    (15, 'Káº¿t Äan Háº­u Ká»³', 'Káº¿t Äan Háº­u Ká»³', 50000, 500, 20, 0.5, 0),
    (16, 'NguyÃªn Anh SÆ¡ Ká»³', 'NguyÃªn Anh SÆ¡ Ká»³', 125000, 1200, 18, 0.7, 0),
    (17, 'NguyÃªn Anh Trung Ká»³', 'NguyÃªn Anh Trung Ká»³', 175000, 1500, 15, 0.7, 0),
    (18, 'NguyÃªn Anh Háº­u Ká»³', 'NguyÃªn Anh Háº­u Ká»³', 245000, 2000, 10, 0.7, 0),
    (19, 'HÃ³a Tháº§n SÆ¡ Ká»³', 'HÃ³a Tháº§n SÆ¡ Ká»³', 600000, -1, 60, 1.0, 0),
    (20, 'HÃ³a Tháº§n Trung Ká»³', 'HÃ³a Tháº§n Trung Ká»³', 840000, -1, 55, 1.0, 0),
    (21, 'HÃ³a Tháº§n Háº­u Ká»³', 'HÃ³a Tháº§n Háº­u Ká»³', 1200000, -1, 30, 1.0, 0),
    (22, 'Luyá»‡n HÆ° SÆ¡ Ká»³', 'Luyá»‡n HÆ° SÆ¡ Ká»³', 3000000, -1, 30, 1.4, 0),
    (23, 'Luyá»‡n HÆ° Trung Ká»³', 'Luyá»‡n HÆ° Trung Ká»³', 4200000, -1, 25, 1.4, 0),
    (24, 'Luyá»‡n HÆ° Háº­u Ká»³', 'Luyá»‡n HÆ° Háº­u Ká»³', 9000000, -1, 15, 1.4, 0),
    (25, 'Há»£p Thá»ƒ SÆ¡ Ká»³', 'Há»£p Thá»ƒ SÆ¡ Ká»³', 20000000, -1, 20, 2.0, 0),
    (26, 'Há»£p Thá»ƒ Trung Ká»³', 'Há»£p Thá»ƒ Trung Ká»³', 28000000, -1, 15, 2.0, 0),
    (27, 'Há»£p Thá»ƒ Háº­u Ká»³', 'Há»£p Thá»ƒ Háº­u Ká»³', 40000000, -1, 10, 2.0, 0),
    (28, 'Äá»™ Kiáº¿p Ká»³', 'Äá»™ Kiáº¿p Ká»³', 100000000, -1, 12, 3.0, 0),
    (29, 'ChÃ¢n TiÃªn SÆ¡ Ká»³', 'ChÃ¢n TiÃªn SÆ¡ Ká»³', 250000000, -1, 6, 3.0, 0),
    (30, 'ChÃ¢n TiÃªn Trung Ká»³', 'ChÃ¢n TiÃªn Trung Ká»³', 350000000, -1, 5, 3.0, 0),
    (31, 'ChÃ¢n TiÃªn Háº­u Ká»³', 'ChÃ¢n TiÃªn Háº­u Ká»³', 500000000, -1, 4, 3.0, 0)
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    stage_name = EXCLUDED.stage_name,
    max_cultivation = EXCLUDED.max_cultivation,
    lifespan = EXCLUDED.lifespan,
    base_breakthrough_rate = EXCLUDED.base_breakthrough_rate,
    absorption_multiplier = EXCLUDED.absorption_multiplier,
    failure_penalty = EXCLUDED.failure_penalty;

INSERT INTO public.spiritual_energy_templates (
    id,
    code,
    name,
    lk_per_minute
)
VALUES
    (1, 'low', 'Low', 0.8),
    (2, 'medium', 'Medium', 1.0),
    (3, 'high', 'High', 1.5),
    (4, 'dense', 'Dense', 2.0)
ON CONFLICT (id) DO UPDATE
SET
    code = EXCLUDED.code,
    name = EXCLUDED.name,
    lk_per_minute = EXCLUDED.lk_per_minute;

INSERT INTO public.potential_stat_upgrade_tiers (
    target_stat,
    tier_index,
    max_upgrade_count,
    potential_cost_per_upgrade,
    stat_gain_per_upgrade,
    is_enabled
)
VALUES
    (1, 1, 5, 10, 10.000000, TRUE),
    (2, 1, 5, 10, 10.000000, TRUE),
    (4, 1, 5, 1, 1.000000, TRUE),
    (5, 1, 5, 1, 1.000000, TRUE),
    (6, 1, 5, 1, 1.000000, TRUE),
    (7, 1, 5, 1, 0.010000, TRUE)
ON CONFLICT (target_stat, tier_index) DO UPDATE
SET
    max_upgrade_count = EXCLUDED.max_upgrade_count,
    potential_cost_per_upgrade = EXCLUDED.potential_cost_per_upgrade,
    stat_gain_per_upgrade = EXCLUDED.stat_gain_per_upgrade,
    is_enabled = EXCLUDED.is_enabled;

INSERT INTO public.map_templates (
    id,
    name,
    map_type,
    client_map_key,
    width,
    height,
    cell_size,
    default_spawn_x,
    default_spawn_y,
    max_public_zone_count,
    max_players_per_zone,
    supports_cave_placement,
    is_private_per_player,
    spiritual_energy
)
VALUES
    (1, 'Player Home', 0, 'map_home_01', 256, 256, 32, 64, 64, 0, 1, false, true, 100),
    (2, 'Starter Plains', 1, 'map_farm_01', 1024, 1024, 64, 128, 128, 20, 20, true, false, 100)
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    map_type = EXCLUDED.map_type,
    client_map_key = EXCLUDED.client_map_key,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    cell_size = EXCLUDED.cell_size,
    default_spawn_x = EXCLUDED.default_spawn_x,
    default_spawn_y = EXCLUDED.default_spawn_y,
    max_public_zone_count = EXCLUDED.max_public_zone_count,
    max_players_per_zone = EXCLUDED.max_players_per_zone,
    supports_cave_placement = EXCLUDED.supports_cave_placement,
    is_private_per_player = EXCLUDED.is_private_per_player,
    spiritual_energy = EXCLUDED.spiritual_energy;

INSERT INTO public.map_zone_slots (
    id,
    map_template_id,
    zone_index,
    spiritual_energy_template_id
)
VALUES
    (2001, 2, 1, 1),
    (2002, 2, 2, 1),
    (2003, 2, 3, 1),
    (2004, 2, 4, 1),
    (2005, 2, 5, 1),
    (2006, 2, 6, 2),
    (2007, 2, 7, 2),
    (2008, 2, 8, 2),
    (2009, 2, 9, 2),
    (2010, 2, 10, 2),
    (2011, 2, 11, 2),
    (2012, 2, 12, 2),
    (2013, 2, 13, 2),
    (2014, 2, 14, 2),
    (2015, 2, 15, 3),
    (2016, 2, 16, 3),
    (2017, 2, 17, 3),
    (2018, 2, 18, 3),
    (2019, 2, 19, 4),
    (2020, 2, 20, 4)
ON CONFLICT (id) DO UPDATE
SET
    map_template_id = EXCLUDED.map_template_id,
    zone_index = EXCLUDED.zone_index,
    spiritual_energy_template_id = EXCLUDED.spiritual_energy_template_id;

INSERT INTO public.map_spawn_points (
    map_template_id,
    code,
    name,
    spawn_category,
    pos_x,
    pos_y,
    description
)
SELECT
    map_template.id,
    'default_entry',
    'Default Entry',
    4,
    map_template.default_spawn_x,
    map_template.default_spawn_y,
    'Generated automatically from map_templates.default_spawn_x/default_spawn_y.'
FROM public.map_templates map_template
ON CONFLICT (map_template_id, code) DO UPDATE
SET
    name = EXCLUDED.name,
    spawn_category = EXCLUDED.spawn_category,
    pos_x = EXCLUDED.pos_x,
    pos_y = EXCLUDED.pos_y,
    description = EXCLUDED.description;

INSERT INTO public.map_template_adjacent_maps (
    map_template_id,
    adjacent_map_template_id
)
VALUES
    (1, 2),
    (2, 1)
ON CONFLICT (map_template_id, adjacent_map_template_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.martial_arts (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    icon character varying(100) NULL,
    quality integer NOT NULL DEFAULT 1,
    category character varying(50) NULL,
    description text NULL,
    description_template text NULL,
    qi_absorption_rate numeric(10,4) NOT NULL DEFAULT 1.0,
    max_stage integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT martial_arts_pkey PRIMARY KEY (id),
    CONSTRAINT martial_arts_code_key UNIQUE (code)
);

ALTER TABLE public.martial_arts
    ADD COLUMN IF NOT EXISTS icon character varying(100) NULL;

UPDATE public.martial_arts
SET icon = code
WHERE icon IS NULL OR btrim(icon) = '';

ALTER TABLE public.martial_arts
    ADD COLUMN IF NOT EXISTS qi_absorption_rate numeric(10,4) NOT NULL DEFAULT 1.0;

UPDATE public.martial_arts
SET qi_absorption_rate = COALESCE(qi_absorption_rate, 1.0)
WHERE qi_absorption_rate IS NULL;

CREATE TABLE IF NOT EXISTS public.martial_art_stages (
    id integer NOT NULL,
    martial_art_id integer NOT NULL,
    stage_level integer NOT NULL,
    exp_required bigint NOT NULL,
    is_bottleneck boolean NOT NULL DEFAULT false,
    breakthrough_base_rate double precision NULL,
    breakthrough_exp_penalty bigint NOT NULL DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT martial_art_stages_pkey PRIMARY KEY (id),
    CONSTRAINT martial_art_stages_martial_art_stage_key UNIQUE (martial_art_id, stage_level),
    CONSTRAINT fk_martial_art_stages_martial_art
        FOREIGN KEY (martial_art_id) REFERENCES public.martial_arts(id)
);

CREATE TABLE IF NOT EXISTS public.martial_art_stage_stat_bonuses (
    id integer NOT NULL,
    martial_art_stage_id integer NOT NULL,
    stat_type integer NOT NULL,
    value numeric(18, 6) NOT NULL,
    value_type integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT martial_art_stage_stat_bonuses_pkey PRIMARY KEY (id),
    CONSTRAINT fk_martial_art_stage_stat_bonuses_stage
        FOREIGN KEY (martial_art_stage_id) REFERENCES public.martial_art_stages(id)
);

CREATE TABLE IF NOT EXISTS public.skills (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    skill_group_code character varying(50) NOT NULL,
    skill_level integer NOT NULL DEFAULT 1,
    skill_type integer NOT NULL,
    skill_category integer NOT NULL DEFAULT 2,
    target_type integer NOT NULL,
    cast_range numeric(10, 4) NOT NULL DEFAULT 1.0,
    cast_time_ms integer NOT NULL DEFAULT 0,
    travel_time_ms integer NOT NULL DEFAULT 0,
    cooldown_ms integer NOT NULL DEFAULT 0,
    description text NULL,
    description_template text NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT skills_pkey PRIMARY KEY (id),
    CONSTRAINT skills_code_key UNIQUE (code),
    CONSTRAINT skills_group_level_key UNIQUE (skill_group_code, skill_level)
);

CREATE TABLE IF NOT EXISTS public.skill_effects (
    id integer NOT NULL,
    skill_id integer NOT NULL,
    effect_type integer NOT NULL,
    order_index integer NOT NULL DEFAULT 0,
    formula_type integer NULL,
    value_type integer NULL,
    base_value numeric(18, 6) NULL,
    ratio_value numeric(18, 6) NULL,
    extra_value numeric(18, 6) NULL,
    chance_value numeric(18, 6) NULL,
    duration_ms integer NULL,
    stat_type integer NULL,
    resource_type integer NULL,
    target_scope integer NULL,
    trigger_timing integer NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT skill_effects_pkey PRIMARY KEY (id),
    CONSTRAINT skill_effects_skill_order_key UNIQUE (skill_id, order_index),
    CONSTRAINT fk_skill_effects_skill
        FOREIGN KEY (skill_id) REFERENCES public.skills(id)
);

CREATE TABLE IF NOT EXISTS public.martial_art_skills (
    id integer NOT NULL,
    martial_art_id integer NOT NULL,
    skill_id integer NOT NULL,
    unlock_stage integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT martial_art_skills_pkey PRIMARY KEY (id),
    CONSTRAINT martial_art_skills_martial_art_skill_key UNIQUE (martial_art_id, skill_id),
    CONSTRAINT fk_martial_art_skills_martial_art
        FOREIGN KEY (martial_art_id) REFERENCES public.martial_arts(id),
    CONSTRAINT fk_martial_art_skills_skill
        FOREIGN KEY (skill_id) REFERENCES public.skills(id)
);

CREATE TABLE IF NOT EXISTS public.player_martial_arts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    martial_art_id integer NOT NULL,
    current_stage integer NOT NULL DEFAULT 1,
    current_exp bigint NOT NULL DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT player_martial_arts_player_martial_art_key UNIQUE (player_id, martial_art_id),
    CONSTRAINT fk_player_martial_arts_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_martial_arts_martial_art
        FOREIGN KEY (martial_art_id) REFERENCES public.martial_arts(id)
);

CREATE TABLE IF NOT EXISTS public.player_skills (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    skill_id integer NOT NULL,
    skill_group_code character varying(50) NOT NULL,
    source_type integer NOT NULL DEFAULT 1,
    source_martial_art_id integer NULL,
    source_martial_art_skill_id integer NULL,
    unlocked_at timestamp without time zone DEFAULT now(),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT player_skills_player_group_key UNIQUE (player_id, skill_group_code),
    CONSTRAINT fk_player_skills_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_skills_skill
        FOREIGN KEY (skill_id) REFERENCES public.skills(id),
    CONSTRAINT fk_player_skills_source_martial_art
        FOREIGN KEY (source_martial_art_id) REFERENCES public.martial_arts(id),
    CONSTRAINT fk_player_skills_source_martial_art_skill
        FOREIGN KEY (source_martial_art_skill_id) REFERENCES public.martial_art_skills(id)
);

CREATE TABLE IF NOT EXISTS public.player_skill_loadouts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    slot_index integer NOT NULL,
    player_skill_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT player_skill_loadouts_player_slot_key UNIQUE (player_id, slot_index),
    CONSTRAINT fk_player_skill_loadouts_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_skill_loadouts_player_skill
        FOREIGN KEY (player_skill_id) REFERENCES public.player_skills(id)
);

CREATE TABLE IF NOT EXISTS public.item_templates (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    item_type integer NOT NULL,
    rarity integer NOT NULL DEFAULT 1,
    max_stack integer NOT NULL DEFAULT 1,
    is_tradeable boolean NOT NULL DEFAULT true,
    is_droppable boolean NOT NULL DEFAULT true,
    is_destroyable boolean NOT NULL DEFAULT true,
    icon character varying(255) NULL,
    background_icon character varying(255) NULL,
    description text NULL,
    description_template text NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT item_templates_pkey PRIMARY KEY (id),
    CONSTRAINT item_templates_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.player_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NULL,
    item_template_id integer NOT NULL,
    location_type integer NOT NULL DEFAULT 1,
    quantity integer NOT NULL DEFAULT 1,
    is_bound boolean NOT NULL DEFAULT false,
    acquired_at timestamp without time zone NOT NULL DEFAULT now(),
    expire_at timestamp without time zone NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT fk_player_items_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_items_item_template
        FOREIGN KEY (item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.equipment_templates (
    item_template_id integer NOT NULL,
    slot_type integer NOT NULL,
    equipment_type integer NOT NULL,
    level_requirement integer NOT NULL DEFAULT 1,
    CONSTRAINT equipment_templates_pkey PRIMARY KEY (item_template_id),
    CONSTRAINT fk_equipment_templates_item_template
        FOREIGN KEY (item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.equipment_template_stats (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_template_id integer NOT NULL,
    stat_type integer NOT NULL,
    value numeric(18, 6) NOT NULL,
    value_type integer NOT NULL,
    CONSTRAINT fk_equipment_template_stats_equipment_template
        FOREIGN KEY (equipment_template_id) REFERENCES public.equipment_templates(item_template_id)
);

CREATE TABLE IF NOT EXISTS public.player_equipments (
    player_item_id bigint NOT NULL,
    equipped_slot integer NULL,
    enhance_level integer NOT NULL DEFAULT 0,
    durability integer NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT player_equipments_pkey PRIMARY KEY (player_item_id),
    CONSTRAINT fk_player_equipments_player_item
        FOREIGN KEY (player_item_id) REFERENCES public.player_items(id)
);

CREATE TABLE IF NOT EXISTS public.player_equipment_stat_bonuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_item_id bigint NOT NULL,
    stat_type integer NOT NULL,
    value numeric(18, 6) NOT NULL,
    value_type integer NOT NULL,
    source_type integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT fk_player_equipment_stat_bonuses_player_item
        FOREIGN KEY (player_item_id) REFERENCES public.player_items(id)
);

CREATE TABLE IF NOT EXISTS public.craft_recipes (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    result_item_template_id integer NOT NULL,
    result_quantity integer NOT NULL DEFAULT 1,
    success_rate double precision NOT NULL DEFAULT 1,
    mutation_rate double precision NOT NULL DEFAULT 0,
    mutation_rate_cap double precision NOT NULL DEFAULT 0,
    cost_currency_type integer NULL,
    cost_currency_value bigint NOT NULL DEFAULT 0,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT craft_recipes_pkey PRIMARY KEY (id),
    CONSTRAINT craft_recipes_code_key UNIQUE (code),
    CONSTRAINT fk_craft_recipes_result_item_template
        FOREIGN KEY (result_item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.craft_recipe_requirements (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    craft_recipe_id integer NOT NULL,
    required_item_template_id integer NOT NULL,
    required_quantity integer NOT NULL DEFAULT 1,
    consume_mode integer NOT NULL,
    is_optional boolean NOT NULL DEFAULT false,
    mutation_bonus_rate double precision NOT NULL DEFAULT 0,
    CONSTRAINT fk_craft_recipe_requirements_recipe
        FOREIGN KEY (craft_recipe_id) REFERENCES public.craft_recipes(id),
    CONSTRAINT fk_craft_recipe_requirements_item_template
        FOREIGN KEY (required_item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.craft_recipe_mutation_bonuses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    craft_recipe_id integer NOT NULL,
    stat_type integer NOT NULL,
    value numeric(18, 6) NOT NULL,
    value_type integer NOT NULL,
    CONSTRAINT fk_craft_recipe_mutation_bonuses_recipe
        FOREIGN KEY (craft_recipe_id) REFERENCES public.craft_recipes(id)
);

CREATE TABLE IF NOT EXISTS public.martial_art_book_templates (
    item_template_id integer NOT NULL,
    martial_art_id integer NOT NULL,
    CONSTRAINT martial_art_book_templates_pkey PRIMARY KEY (item_template_id),
    CONSTRAINT fk_martial_art_book_templates_item_template
        FOREIGN KEY (item_template_id) REFERENCES public.item_templates(id),
    CONSTRAINT fk_martial_art_book_templates_martial_art
        FOREIGN KEY (martial_art_id) REFERENCES public.martial_arts(id)
);

CREATE TABLE IF NOT EXISTS public.player_caves (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_character_id uuid NOT NULL,
    map_template_id integer NOT NULL,
    zone_index integer NOT NULL DEFAULT 0,
    is_home boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT player_caves_owner_map_zone_key UNIQUE (owner_character_id, map_template_id, zone_index),
    CONSTRAINT fk_player_caves_owner
        FOREIGN KEY (owner_character_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_caves_map_template
        FOREIGN KEY (map_template_id) REFERENCES public.map_templates(id)
);

CREATE TABLE IF NOT EXISTS public.player_garden_plots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    cave_id bigint NOT NULL,
    plot_index integer NOT NULL,
    current_soil_player_item_id bigint NULL,
    current_player_herb_id bigint NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT player_garden_plots_cave_plot_key UNIQUE (cave_id, plot_index),
    CONSTRAINT fk_player_garden_plots_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_garden_plots_cave
        FOREIGN KEY (cave_id) REFERENCES public.player_caves(id),
    CONSTRAINT fk_player_garden_plots_soil_player_item
        FOREIGN KEY (current_soil_player_item_id) REFERENCES public.player_items(id)
);

CREATE TABLE IF NOT EXISTS public.soil_templates (
    item_template_id integer NOT NULL,
    growth_speed_rate numeric(10,4) NOT NULL DEFAULT 1.0,
    max_active_seconds bigint NOT NULL,
    description text NULL,
    CONSTRAINT soil_templates_pkey PRIMARY KEY (item_template_id),
    CONSTRAINT fk_soil_templates_item_template
        FOREIGN KEY (item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.player_soils (
    player_item_id bigint NOT NULL,
    total_used_seconds bigint NOT NULL DEFAULT 0,
    state integer NOT NULL,
    inserted_plot_id bigint NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT player_soils_pkey PRIMARY KEY (player_item_id),
    CONSTRAINT fk_player_soils_player_item
        FOREIGN KEY (player_item_id) REFERENCES public.player_items(id),
    CONSTRAINT fk_player_soils_inserted_plot
        FOREIGN KEY (inserted_plot_id) REFERENCES public.player_garden_plots(id)
);

CREATE TABLE IF NOT EXISTS public.herb_templates (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    seed_item_template_id integer NOT NULL,
    replant_item_template_id integer NULL,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT herb_templates_pkey PRIMARY KEY (id),
    CONSTRAINT herb_templates_code_key UNIQUE (code),
    CONSTRAINT herb_templates_seed_item_template_key UNIQUE (seed_item_template_id),
    CONSTRAINT herb_templates_replant_item_template_key UNIQUE (replant_item_template_id),
    CONSTRAINT fk_herb_templates_seed_item_template
        FOREIGN KEY (seed_item_template_id) REFERENCES public.item_templates(id),
    CONSTRAINT fk_herb_templates_replant_item_template
        FOREIGN KEY (replant_item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.herb_growth_stage_configs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    herb_template_id integer NOT NULL,
    stage integer NOT NULL,
    stage_name character varying(50) NOT NULL,
    required_growth_seconds bigint NOT NULL,
    CONSTRAINT herb_growth_stage_configs_herb_stage_key UNIQUE (herb_template_id, stage),
    CONSTRAINT fk_herb_growth_stage_configs_herb_template
        FOREIGN KEY (herb_template_id) REFERENCES public.herb_templates(id)
);

CREATE TABLE IF NOT EXISTS public.player_herbs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    herb_template_id integer NOT NULL,
    current_stage integer NOT NULL,
    planted_at timestamp without time zone NULL,
    accumulated_growth_seconds bigint NOT NULL DEFAULT 0,
    state integer NOT NULL,
    current_plot_id bigint NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT fk_player_herbs_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_herbs_herb_template
        FOREIGN KEY (herb_template_id) REFERENCES public.herb_templates(id),
    CONSTRAINT fk_player_herbs_current_plot
        FOREIGN KEY (current_plot_id) REFERENCES public.player_garden_plots(id)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_player_garden_plots_current_herb'
    ) THEN
        ALTER TABLE public.player_garden_plots
            ADD CONSTRAINT fk_player_garden_plots_current_herb
            FOREIGN KEY (current_player_herb_id) REFERENCES public.player_herbs(id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.herb_harvest_outputs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    herb_template_id integer NOT NULL,
    required_stage integer NOT NULL,
    output_type integer NOT NULL,
    result_item_template_id integer NOT NULL,
    result_quantity integer NOT NULL DEFAULT 1,
    output_chance double precision NOT NULL DEFAULT 1,
    CONSTRAINT fk_herb_harvest_outputs_herb_template
        FOREIGN KEY (herb_template_id) REFERENCES public.herb_templates(id),
    CONSTRAINT fk_herb_harvest_outputs_item_template
        FOREIGN KEY (result_item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.pill_templates (
    item_template_id integer NOT NULL,
    pill_category integer NOT NULL,
    usage_type integer NOT NULL,
    cooldown_ms integer NULL,
    CONSTRAINT pill_templates_pkey PRIMARY KEY (item_template_id),
    CONSTRAINT fk_pill_templates_item_template
        FOREIGN KEY (item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.pill_effects (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pill_template_id integer NOT NULL,
    effect_type integer NOT NULL,
    order_index integer NOT NULL DEFAULT 0,
    value_type integer NULL,
    base_value numeric(18, 6) NULL,
    ratio_value numeric(18, 6) NULL,
    duration_ms integer NULL,
    stat_type integer NULL,
    note text NULL,
    CONSTRAINT pill_effects_pill_order_key UNIQUE (pill_template_id, order_index),
    CONSTRAINT fk_pill_effects_pill_template
        FOREIGN KEY (pill_template_id) REFERENCES public.pill_templates(item_template_id)
);

CREATE TABLE IF NOT EXISTS public.pill_recipe_templates (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    recipe_book_item_template_id integer NOT NULL,
    result_pill_item_template_id integer NOT NULL,
    description text NULL,
    base_success_rate double precision NOT NULL DEFAULT 1,
    success_rate_cap double precision NULL,
    mutation_rate double precision NOT NULL DEFAULT 0,
    mutation_rate_cap double precision NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT pill_recipe_templates_pkey PRIMARY KEY (id),
    CONSTRAINT pill_recipe_templates_code_key UNIQUE (code),
    CONSTRAINT pill_recipe_templates_recipe_book_item_template_key UNIQUE (recipe_book_item_template_id),
    CONSTRAINT fk_pill_recipe_templates_recipe_book_item_template
        FOREIGN KEY (recipe_book_item_template_id) REFERENCES public.item_templates(id),
    CONSTRAINT fk_pill_recipe_templates_result_pill_item_template
        FOREIGN KEY (result_pill_item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.pill_recipe_inputs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pill_recipe_template_id integer NOT NULL,
    required_item_template_id integer NOT NULL,
    required_quantity integer NOT NULL DEFAULT 1,
    consume_mode integer NOT NULL,
    is_optional boolean NOT NULL DEFAULT false,
    success_rate_bonus double precision NOT NULL DEFAULT 0,
    mutation_bonus_rate double precision NOT NULL DEFAULT 0,
    required_herb_maturity integer NOT NULL DEFAULT 0,
    CONSTRAINT fk_pill_recipe_inputs_recipe
        FOREIGN KEY (pill_recipe_template_id) REFERENCES public.pill_recipe_templates(id),
    CONSTRAINT fk_pill_recipe_inputs_item_template
        FOREIGN KEY (required_item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.player_pill_recipes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    pill_recipe_template_id integer NOT NULL,
    learned_at timestamp without time zone NOT NULL DEFAULT now(),
    total_craft_count integer NOT NULL DEFAULT 0,
    current_success_rate_bonus double precision NOT NULL DEFAULT 0,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT player_pill_recipes_player_recipe_key UNIQUE (player_id, pill_recipe_template_id),
    CONSTRAINT fk_player_pill_recipes_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_pill_recipes_recipe
        FOREIGN KEY (pill_recipe_template_id) REFERENCES public.pill_recipe_templates(id)
);

CREATE TABLE IF NOT EXISTS public.pill_recipe_mastery_stages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pill_recipe_template_id integer NOT NULL,
    required_total_craft_count integer NOT NULL,
    success_rate_bonus double precision NOT NULL DEFAULT 0,
    CONSTRAINT pill_recipe_mastery_stages_recipe_count_key UNIQUE (pill_recipe_template_id, required_total_craft_count),
    CONSTRAINT fk_pill_recipe_mastery_stages_recipe
        FOREIGN KEY (pill_recipe_template_id) REFERENCES public.pill_recipe_templates(id)
);

CREATE TABLE IF NOT EXISTS public.enemy_templates (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    kind integer NOT NULL,
    max_hp integer NOT NULL,
    base_attack integer NOT NULL DEFAULT 0,
    base_move_speed numeric(10, 4) NOT NULL DEFAULT 100.0,
    patrol_radius numeric(10, 4) NOT NULL DEFAULT 0,
    detection_radius numeric(10, 4) NOT NULL DEFAULT 0,
    combat_radius numeric(10, 4) NOT NULL DEFAULT 0,
    enable_out_of_combat_restore boolean NOT NULL DEFAULT true,
    out_of_combat_restore_delay_seconds integer NOT NULL DEFAULT 20,
    minimum_skill_interval_ms integer NOT NULL DEFAULT 1000,
    cultivation_reward_total bigint NOT NULL DEFAULT 0,
    potential_reward_total integer NOT NULL DEFAULT 0,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT enemy_templates_pkey PRIMARY KEY (id),
    CONSTRAINT enemy_templates_code_key UNIQUE (code)
);

ALTER TABLE public.enemy_templates
    ADD COLUMN IF NOT EXISTS base_move_speed numeric(10, 4) NOT NULL DEFAULT 100.0,
    ADD COLUMN IF NOT EXISTS enable_out_of_combat_restore boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS out_of_combat_restore_delay_seconds integer NOT NULL DEFAULT 20;

UPDATE public.enemy_templates
SET
    base_move_speed = CASE
        WHEN code = 'wood_doll' THEN 0
        ELSE COALESCE(base_move_speed, 100.0)
    END,
    enable_out_of_combat_restore = COALESCE(enable_out_of_combat_restore, true),
    out_of_combat_restore_delay_seconds = COALESCE(out_of_combat_restore_delay_seconds, 20)
WHERE base_move_speed IS NULL
   OR enable_out_of_combat_restore IS NULL
   OR out_of_combat_restore_delay_seconds IS NULL;

CREATE TABLE IF NOT EXISTS public.enemy_template_skills (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enemy_template_id integer NOT NULL,
    skill_id integer NOT NULL,
    order_index integer NOT NULL DEFAULT 0,
    CONSTRAINT enemy_template_skills_enemy_order_key UNIQUE (enemy_template_id, order_index),
    CONSTRAINT fk_enemy_template_skills_enemy
        FOREIGN KEY (enemy_template_id) REFERENCES public.enemy_templates(id),
    CONSTRAINT fk_enemy_template_skills_skill
        FOREIGN KEY (skill_id) REFERENCES public.skills(id)
);

CREATE TABLE IF NOT EXISTS public.enemy_reward_rules (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enemy_template_id integer NOT NULL,
    delivery_type integer NOT NULL,
    target_rule integer NOT NULL,
    game_random_table_id integer NOT NULL,
    roll_count integer NOT NULL DEFAULT 1,
    ownership_duration_seconds integer NULL,
    free_for_all_duration_seconds integer NULL,
    minimum_damage_parts_per_million integer NOT NULL DEFAULT 0,
    order_index integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT enemy_reward_rules_enemy_order_key UNIQUE (enemy_template_id, order_index),
    CONSTRAINT fk_enemy_reward_rules_enemy
        FOREIGN KEY (enemy_template_id) REFERENCES public.enemy_templates(id),
    CONSTRAINT fk_enemy_reward_rules_random_table
        FOREIGN KEY (game_random_table_id) REFERENCES public.game_random_tables(id)
);

CREATE TABLE IF NOT EXISTS public.map_enemy_spawn_groups (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    map_template_id integer NOT NULL,
    runtime_scope integer NOT NULL DEFAULT 0,
    zone_index integer NULL,
    spawn_mode integer NOT NULL DEFAULT 1,
    is_boss_spawn boolean NOT NULL DEFAULT false,
    max_alive integer NOT NULL DEFAULT 1,
    respawn_seconds integer NOT NULL DEFAULT 30,
    initial_spawn_delay_seconds integer NOT NULL DEFAULT 0,
    center_x real NOT NULL,
    center_y real NOT NULL,
    spawn_radius real NOT NULL DEFAULT 0,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT map_enemy_spawn_groups_pkey PRIMARY KEY (id),
    CONSTRAINT map_enemy_spawn_groups_code_key UNIQUE (code),
    CONSTRAINT fk_map_enemy_spawn_groups_map
        FOREIGN KEY (map_template_id) REFERENCES public.map_templates(id)
);

CREATE TABLE IF NOT EXISTS public.map_enemy_spawn_entries (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spawn_group_id integer NOT NULL,
    enemy_template_id integer NOT NULL,
    weight integer NOT NULL DEFAULT 1,
    order_index integer NOT NULL DEFAULT 0,
    CONSTRAINT map_enemy_spawn_entries_group_order_key UNIQUE (spawn_group_id, order_index),
    CONSTRAINT fk_map_enemy_spawn_entries_group
        FOREIGN KEY (spawn_group_id) REFERENCES public.map_enemy_spawn_groups(id),
    CONSTRAINT fk_map_enemy_spawn_entries_enemy
        FOREIGN KEY (enemy_template_id) REFERENCES public.enemy_templates(id)
);

CREATE TABLE IF NOT EXISTS public.map_instance_configs (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    map_template_id integer NOT NULL,
    instance_mode integer NOT NULL,
    duration_seconds integer NULL,
    idle_destroy_seconds integer NULL,
    completion_rule integer NOT NULL DEFAULT 0,
    complete_destroy_delay_seconds integer NULL,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT map_instance_configs_pkey PRIMARY KEY (id),
    CONSTRAINT map_instance_configs_code_key UNIQUE (code),
    CONSTRAINT map_instance_configs_map_template_key UNIQUE (map_template_id),
    CONSTRAINT fk_map_instance_configs_map
        FOREIGN KEY (map_template_id) REFERENCES public.map_templates(id)
);

INSERT INTO public.enemy_templates (
    id,
    code,
    name,
    kind,
    max_hp,
    base_attack,
    base_move_speed,
    patrol_radius,
    detection_radius,
    combat_radius,
    enable_out_of_combat_restore,
    out_of_combat_restore_delay_seconds,
    minimum_skill_interval_ms,
    cultivation_reward_total,
    potential_reward_total,
    description)
VALUES (
    1003,
    'wood_doll',
    'Nguoi Rom Luyen Cong',
    1,
    1000,
    0,
    0,
    0,
    0,
    0,
    true,
    20,
    1000,
    0,
    0,
    'Hinh nom dung yen trong dong phu de test damage, skill va VFX.')
ON CONFLICT (code) DO UPDATE
SET
    name = EXCLUDED.name,
    kind = EXCLUDED.kind,
    max_hp = EXCLUDED.max_hp,
    base_attack = EXCLUDED.base_attack,
    base_move_speed = EXCLUDED.base_move_speed,
    patrol_radius = EXCLUDED.patrol_radius,
    detection_radius = EXCLUDED.detection_radius,
    combat_radius = EXCLUDED.combat_radius,
    enable_out_of_combat_restore = EXCLUDED.enable_out_of_combat_restore,
    out_of_combat_restore_delay_seconds = EXCLUDED.out_of_combat_restore_delay_seconds,
    minimum_skill_interval_ms = EXCLUDED.minimum_skill_interval_ms,
    cultivation_reward_total = EXCLUDED.cultivation_reward_total,
    potential_reward_total = EXCLUDED.potential_reward_total,
    description = EXCLUDED.description;

INSERT INTO public.map_enemy_spawn_groups (
    id,
    code,
    name,
    map_template_id,
    runtime_scope,
    zone_index,
    spawn_mode,
    is_boss_spawn,
    max_alive,
    respawn_seconds,
    initial_spawn_delay_seconds,
    center_x,
    center_y,
    spawn_radius,
    description)
VALUES (
    3003,
    'home_wood_doll_spawn',
    'Home Wood Doll Spawn',
    1,
    2,
    NULL,
    1,
    FALSE,
    1,
    2,
    0,
    500,
    125,
    0,
    'Sinh 1 nguoi rom trong dong phu rieng cua moi nhan vat.')
ON CONFLICT (code) DO UPDATE
SET
    name = EXCLUDED.name,
    map_template_id = EXCLUDED.map_template_id,
    runtime_scope = EXCLUDED.runtime_scope,
    zone_index = EXCLUDED.zone_index,
    spawn_mode = EXCLUDED.spawn_mode,
    is_boss_spawn = EXCLUDED.is_boss_spawn,
    max_alive = EXCLUDED.max_alive,
    respawn_seconds = EXCLUDED.respawn_seconds,
    initial_spawn_delay_seconds = EXCLUDED.initial_spawn_delay_seconds,
    center_x = EXCLUDED.center_x,
    center_y = EXCLUDED.center_y,
    spawn_radius = EXCLUDED.spawn_radius,
    description = EXCLUDED.description;

INSERT INTO public.map_enemy_spawn_entries (
    spawn_group_id,
    enemy_template_id,
    weight,
    order_index)
SELECT
    spawn_group.id,
    enemy_template.id,
    1,
    0
FROM public.map_enemy_spawn_groups spawn_group
JOIN public.enemy_templates enemy_template
    ON enemy_template.code = 'wood_doll'
WHERE spawn_group.code = 'home_wood_doll_spawn'
ON CONFLICT (spawn_group_id, order_index) DO UPDATE
SET
    enemy_template_id = EXCLUDED.enemy_template_id,
    weight = EXCLUDED.weight;

COMMIT;

BEGIN;

CREATE TABLE IF NOT EXISTS public.game_configs (
    config_key character varying(100) PRIMARY KEY,
    config_value character varying(100) NOT NULL,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now()
);

INSERT INTO public.game_configs (config_key, config_value, description)
VALUES
    ('network.reconnect_resume_window_seconds', '3', 'So giay server giu resume token/session sau khi mat ket noi de reconnect.'),
    ('world.portal_validation_buffer_server_units', '4', 'Buffer them vao interaction radius khi server validate di qua portal.'),
    ('combat.skill_range_grace_buffer_units', '12', 'Buffer them vao tam cast skill khi server validate attack target.'),
    ('combat_death.return_home_recovery_ratio', '0.8', 'Ti le HP/MP hoi lai khi player combat dead va duoc dua ve home.'),
    ('item_drop.player_drop_ownership_seconds', '10', 'So giay item vut tu inventory con ownership rieng cho nguoi vut.'),
    ('item_drop.player_drop_free_for_all_seconds', '50', 'So giay sau giai doan ownership de item vut tu inventory ton tai o free-for-all.'),
    ('item_drop.enemy_drop_default_ownership_seconds', '30', 'So giay ownership mac dinh cho ground reward roi tu enemy khi reward rule khong chi dinh.'),
    ('item_drop.enemy_drop_default_free_for_all_seconds', '30', 'So giay free-for-all mac dinh cho ground reward roi tu enemy khi reward rule khong chi dinh.'),
    ('world.empty_public_instance_lifetime_seconds', '120', 'So giay mot public instance rong duoc giu truoc khi bi huy.'),
    ('cultivation.potential_per_cultivation_point', '1', 'So potential duoc quy doi tu moi cultivation point khi settle cultivation.'),
    ('cultivation.settlement_interval_seconds', '300', 'Chu ky settle cultivation theo giay.'),
    ('character.home_garden_plot_count', '8', 'So o vuon mac dinh khi tao home cave moi.'),
    ('character.starter_basic_skill_id', '0', 'Skill id basic mac dinh duoc grant cho nhan vat moi.'),
    ('character.starter_basic_skill_slot_index', '1', 'Loadout slot mac dinh dung de gan starter basic skill.'),
    ('skill.max_loadout_slot_count', '5', 'So slot loadout skill toi da cua nhan vat.')
ON CONFLICT (config_key) DO UPDATE
SET
    config_value = EXCLUDED.config_value,
    description = EXCLUDED.description,
    updated_at = now();

COMMIT;
