BEGIN;

CREATE TABLE IF NOT EXISTS public.player_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    notification_type integer NOT NULL,
    source_type integer NOT NULL DEFAULT 0,
    source_id bigint NULL,
    title text NOT NULL,
    message text NOT NULL,
    display_item_template_id integer NULL,
    payload_json text NULL,
    created_at_utc timestamp without time zone NOT NULL DEFAULT timezone('utc', now()),
    read_at_utc timestamp without time zone NULL,
    CONSTRAINT fk_player_notifications_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_notifications_item_template
        FOREIGN KEY (display_item_template_id) REFERENCES public.item_templates(id)
);

CREATE INDEX IF NOT EXISTS idx_player_notifications_player_read
    ON public.player_notifications(player_id, read_at_utc, created_at_utc);

CREATE UNIQUE INDEX IF NOT EXISTS idx_player_notifications_player_source_unique
    ON public.player_notifications(player_id, source_type, source_id)
    WHERE source_id IS NOT NULL;

INSERT INTO public.player_notifications (
    player_id,
    notification_type,
    source_type,
    source_id,
    title,
    message,
    display_item_template_id,
    payload_json,
    created_at_utc
)
SELECT
    s.player_id,
    2,
    1,
    s.id,
    COALESCE(NULLIF(s.result_payload_json::jsonb ->> 'title', ''), 'Thong bao'),
    COALESCE(NULLIF(s.result_payload_json::jsonb ->> 'message', ''), 'Thong bao moi.'),
    NULLIF(s.result_payload_json::jsonb ->> 'displayItemTemplateId', '')::integer,
    s.result_payload_json,
    COALESCE(s.completed_at_utc, s.updated_at_utc, timezone('utc', now()))
FROM public.player_practice_sessions s
WHERE s.practice_state = 3
  AND s.result_payload_json IS NOT NULL
ON CONFLICT DO NOTHING;

UPDATE public.player_practice_sessions
SET
    practice_state = 4,
    result_acknowledged_at_utc = COALESCE(result_acknowledged_at_utc, completed_at_utc, timezone('utc', now())),
    updated_at_utc = timezone('utc', now())
WHERE practice_state = 3;

COMMIT;
