BEGIN;

ALTER TABLE public.pill_recipe_templates
    ADD COLUMN IF NOT EXISTS craft_duration_seconds bigint NOT NULL DEFAULT 10;

UPDATE public.pill_recipe_templates
SET craft_duration_seconds = 10
WHERE craft_duration_seconds IS NULL
   OR craft_duration_seconds <= 0;

CREATE TABLE IF NOT EXISTS public.player_practice_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    practice_type integer NOT NULL,
    practice_state integer NOT NULL,
    definition_id integer NOT NULL,
    current_map_id integer NOT NULL,
    title character varying(200) NOT NULL,
    total_duration_seconds bigint NOT NULL,
    accumulated_active_seconds bigint NOT NULL DEFAULT 0,
    cancel_locked_progress double precision NOT NULL DEFAULT 0.8,
    request_payload_json text NULL,
    result_payload_json text NULL,
    started_at_utc timestamp without time zone NOT NULL DEFAULT now(),
    last_resumed_at_utc timestamp without time zone NULL,
    paused_at_utc timestamp without time zone NULL,
    completed_at_utc timestamp without time zone NULL,
    result_acknowledged_at_utc timestamp without time zone NULL,
    updated_at_utc timestamp without time zone NOT NULL DEFAULT now(),
    created_at_utc timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT fk_player_practice_sessions_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id)
);

CREATE INDEX IF NOT EXISTS idx_player_practice_sessions_player_updated
    ON public.player_practice_sessions(player_id, updated_at_utc DESC);

CREATE INDEX IF NOT EXISTS idx_player_practice_sessions_state
    ON public.player_practice_sessions(player_id, practice_state, practice_type);

COMMIT;
