BEGIN;

ALTER TABLE IF EXISTS public.equipment_templates
    DROP COLUMN IF EXISTS slot_type;

ALTER TABLE IF EXISTS public.player_skills
    ADD COLUMN IF NOT EXISTS source_player_item_id bigint NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_player_skills_source_player_item'
    ) THEN
        ALTER TABLE public.player_skills
            ADD CONSTRAINT fk_player_skills_source_player_item
            FOREIGN KEY (source_player_item_id) REFERENCES public.player_items(id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.equipment_template_skill_grants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_template_id integer NOT NULL,
    skill_id integer NOT NULL,
    required_realm_template_id integer NULL,
    display_order integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT equipment_template_skill_grants_equipment_skill_key UNIQUE (equipment_template_id, skill_id),
    CONSTRAINT fk_equipment_template_skill_grants_equipment_template
        FOREIGN KEY (equipment_template_id) REFERENCES public.equipment_templates(item_template_id),
    CONSTRAINT fk_equipment_template_skill_grants_skill
        FOREIGN KEY (skill_id) REFERENCES public.skills(id),
    CONSTRAINT fk_equipment_template_skill_grants_required_realm
        FOREIGN KEY (required_realm_template_id) REFERENCES public.realm_templates(id)
);

CREATE TABLE IF NOT EXISTS public.player_skill_grant_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    player_skill_id bigint NOT NULL,
    source_type integer NOT NULL,
    granted_skill_id integer NOT NULL,
    source_player_item_id bigint NULL,
    source_equipment_template_id integer NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT player_skill_grant_sources_player_skill_source_item_key UNIQUE (player_skill_id, source_player_item_id),
    CONSTRAINT fk_player_skill_grant_sources_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_skill_grant_sources_player_skill
        FOREIGN KEY (player_skill_id) REFERENCES public.player_skills(id),
    CONSTRAINT fk_player_skill_grant_sources_granted_skill
        FOREIGN KEY (granted_skill_id) REFERENCES public.skills(id),
    CONSTRAINT fk_player_skill_grant_sources_player_item
        FOREIGN KEY (source_player_item_id) REFERENCES public.player_items(id),
    CONSTRAINT fk_player_skill_grant_sources_equipment_template
        FOREIGN KEY (source_equipment_template_id) REFERENCES public.equipment_templates(item_template_id)
);

INSERT INTO public.game_configs (config_key, config_value, description)
VALUES
    ('character.equipment_slot_count', '4', 'So o trang bi co dinh hien tai cua nhan vat.')
ON CONFLICT (config_key) DO UPDATE
SET
    config_value = EXCLUDED.config_value,
    description = EXCLUDED.description,
    updated_at = now();

COMMIT;
