CREATE TABLE IF NOT EXISTS public.player_caves (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_character_id uuid NOT NULL,
    map_template_id integer NOT NULL,
    zone_index integer NOT NULL DEFAULT 0,
    is_home boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT player_caves_owner_map_zone_key UNIQUE (owner_character_id, map_template_id, zone_index),
    CONSTRAINT fk_player_caves_owner
        FOREIGN KEY (owner_character_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_caves_map_template
        FOREIGN KEY (map_template_id) REFERENCES public.map_templates(id)
);

CREATE TABLE IF NOT EXISTS public.player_garden_plots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    cave_id bigint NOT NULL,
    plot_index integer NOT NULL,
    current_soil_player_item_id bigint NULL,
    current_player_herb_id bigint NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT player_garden_plots_cave_plot_key UNIQUE (cave_id, plot_index),
    CONSTRAINT fk_player_garden_plots_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_garden_plots_cave
        FOREIGN KEY (cave_id) REFERENCES public.player_caves(id),
    CONSTRAINT fk_player_garden_plots_soil_player_item
        FOREIGN KEY (current_soil_player_item_id) REFERENCES public.player_items(id)
);

CREATE TABLE IF NOT EXISTS public.soil_templates (
    item_template_id integer NOT NULL,
    growth_speed_rate numeric(10,4) NOT NULL DEFAULT 1.0,
    max_active_seconds bigint NOT NULL,
    description text NULL,
    CONSTRAINT soil_templates_pkey PRIMARY KEY (item_template_id),
    CONSTRAINT fk_soil_templates_item_template
        FOREIGN KEY (item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.player_soils (
    player_item_id bigint NOT NULL,
    total_used_seconds bigint NOT NULL DEFAULT 0,
    state integer NOT NULL,
    inserted_plot_id bigint NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT player_soils_pkey PRIMARY KEY (player_item_id),
    CONSTRAINT fk_player_soils_player_item
        FOREIGN KEY (player_item_id) REFERENCES public.player_items(id),
    CONSTRAINT fk_player_soils_inserted_plot
        FOREIGN KEY (inserted_plot_id) REFERENCES public.player_garden_plots(id)
);

CREATE TABLE IF NOT EXISTS public.herb_templates (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    seed_item_template_id integer NOT NULL,
    replant_item_template_id integer NULL,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT herb_templates_pkey PRIMARY KEY (id),
    CONSTRAINT herb_templates_code_key UNIQUE (code),
    CONSTRAINT herb_templates_seed_item_template_key UNIQUE (seed_item_template_id),
    CONSTRAINT herb_templates_replant_item_template_key UNIQUE (replant_item_template_id),
    CONSTRAINT fk_herb_templates_seed_item_template
        FOREIGN KEY (seed_item_template_id) REFERENCES public.item_templates(id),
    CONSTRAINT fk_herb_templates_replant_item_template
        FOREIGN KEY (replant_item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.herb_growth_stage_configs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    herb_template_id integer NOT NULL,
    stage integer NOT NULL,
    stage_name character varying(50) NOT NULL,
    required_growth_seconds bigint NOT NULL,
    CONSTRAINT herb_growth_stage_configs_herb_stage_key UNIQUE (herb_template_id, stage),
    CONSTRAINT fk_herb_growth_stage_configs_herb_template
        FOREIGN KEY (herb_template_id) REFERENCES public.herb_templates(id)
);

CREATE TABLE IF NOT EXISTS public.player_herbs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    herb_template_id integer NOT NULL,
    current_stage integer NOT NULL,
    planted_at timestamp without time zone NULL,
    accumulated_growth_seconds bigint NOT NULL DEFAULT 0,
    state integer NOT NULL,
    current_plot_id bigint NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT fk_player_herbs_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_herbs_herb_template
        FOREIGN KEY (herb_template_id) REFERENCES public.herb_templates(id),
    CONSTRAINT fk_player_herbs_current_plot
        FOREIGN KEY (current_plot_id) REFERENCES public.player_garden_plots(id)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_player_garden_plots_current_herb'
    ) THEN
        ALTER TABLE public.player_garden_plots
            ADD CONSTRAINT fk_player_garden_plots_current_herb
            FOREIGN KEY (current_player_herb_id) REFERENCES public.player_herbs(id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.herb_harvest_outputs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    herb_template_id integer NOT NULL,
    required_stage integer NOT NULL,
    output_type integer NOT NULL,
    result_item_template_id integer NOT NULL,
    result_quantity integer NOT NULL DEFAULT 1,
    output_chance double precision NOT NULL DEFAULT 1,
    CONSTRAINT fk_herb_harvest_outputs_herb_template
        FOREIGN KEY (herb_template_id) REFERENCES public.herb_templates(id),
    CONSTRAINT fk_herb_harvest_outputs_item_template
        FOREIGN KEY (result_item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.pill_templates (
    item_template_id integer NOT NULL,
    pill_category integer NOT NULL,
    usage_type integer NOT NULL,
    cooldown_ms integer NULL,
    CONSTRAINT pill_templates_pkey PRIMARY KEY (item_template_id),
    CONSTRAINT fk_pill_templates_item_template
        FOREIGN KEY (item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.pill_effects (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pill_template_id integer NOT NULL,
    effect_type integer NOT NULL,
    order_index integer NOT NULL DEFAULT 0,
    value_type integer NULL,
    base_value numeric(18, 6) NULL,
    ratio_value numeric(18, 6) NULL,
    duration_ms integer NULL,
    stat_type integer NULL,
    note text NULL,
    CONSTRAINT pill_effects_pill_order_key UNIQUE (pill_template_id, order_index),
    CONSTRAINT fk_pill_effects_pill_template
        FOREIGN KEY (pill_template_id) REFERENCES public.pill_templates(item_template_id)
);

CREATE TABLE IF NOT EXISTS public.pill_recipe_templates (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    recipe_book_item_template_id integer NOT NULL,
    result_pill_item_template_id integer NOT NULL,
    description text NULL,
    base_success_rate double precision NOT NULL DEFAULT 1,
    success_rate_cap double precision NULL,
    mutation_rate double precision NOT NULL DEFAULT 0,
    mutation_rate_cap double precision NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT pill_recipe_templates_pkey PRIMARY KEY (id),
    CONSTRAINT pill_recipe_templates_code_key UNIQUE (code),
    CONSTRAINT pill_recipe_templates_recipe_book_item_template_key UNIQUE (recipe_book_item_template_id),
    CONSTRAINT fk_pill_recipe_templates_recipe_book_item_template
        FOREIGN KEY (recipe_book_item_template_id) REFERENCES public.item_templates(id),
    CONSTRAINT fk_pill_recipe_templates_result_pill_item_template
        FOREIGN KEY (result_pill_item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.pill_recipe_inputs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pill_recipe_template_id integer NOT NULL,
    required_item_template_id integer NOT NULL,
    required_quantity integer NOT NULL DEFAULT 1,
    consume_mode integer NOT NULL,
    is_optional boolean NOT NULL DEFAULT false,
    success_rate_bonus double precision NOT NULL DEFAULT 0,
    mutation_bonus_rate double precision NOT NULL DEFAULT 0,
    required_herb_maturity integer NOT NULL DEFAULT 0,
    CONSTRAINT fk_pill_recipe_inputs_recipe
        FOREIGN KEY (pill_recipe_template_id) REFERENCES public.pill_recipe_templates(id),
    CONSTRAINT fk_pill_recipe_inputs_item_template
        FOREIGN KEY (required_item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.player_pill_recipes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    pill_recipe_template_id integer NOT NULL,
    learned_at timestamp without time zone NOT NULL DEFAULT now(),
    total_craft_count integer NOT NULL DEFAULT 0,
    current_success_rate_bonus double precision NOT NULL DEFAULT 0,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT player_pill_recipes_player_recipe_key UNIQUE (player_id, pill_recipe_template_id),
    CONSTRAINT fk_player_pill_recipes_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_pill_recipes_recipe
        FOREIGN KEY (pill_recipe_template_id) REFERENCES public.pill_recipe_templates(id)
);

CREATE TABLE IF NOT EXISTS public.pill_recipe_mastery_stages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pill_recipe_template_id integer NOT NULL,
    required_total_craft_count integer NOT NULL,
    success_rate_bonus double precision NOT NULL DEFAULT 0,
    CONSTRAINT pill_recipe_mastery_stages_recipe_count_key UNIQUE (pill_recipe_template_id, required_total_craft_count),
    CONSTRAINT fk_pill_recipe_mastery_stages_recipe
        FOREIGN KEY (pill_recipe_template_id) REFERENCES public.pill_recipe_templates(id)
);
