CREATE TABLE IF NOT EXISTS public.enemy_templates (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    kind integer NOT NULL,
    max_hp integer NOT NULL,
    base_attack integer NOT NULL DEFAULT 0,
    patrol_radius numeric(10, 4) NOT NULL DEFAULT 0,
    detection_radius numeric(10, 4) NOT NULL DEFAULT 0,
    combat_radius numeric(10, 4) NOT NULL DEFAULT 0,
    minimum_skill_interval_ms integer NOT NULL DEFAULT 1000,
    cultivation_reward_total bigint NOT NULL DEFAULT 0,
    potential_reward_total integer NOT NULL DEFAULT 0,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT enemy_templates_pkey PRIMARY KEY (id),
    CONSTRAINT enemy_templates_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.enemy_template_skills (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enemy_template_id integer NOT NULL,
    skill_id integer NOT NULL,
    order_index integer NOT NULL DEFAULT 0,
    CONSTRAINT enemy_template_skills_enemy_order_key UNIQUE (enemy_template_id, order_index),
    CONSTRAINT fk_enemy_template_skills_enemy
        FOREIGN KEY (enemy_template_id) REFERENCES public.enemy_templates(id),
    CONSTRAINT fk_enemy_template_skills_skill
        FOREIGN KEY (skill_id) REFERENCES public.skills(id)
);

CREATE TABLE IF NOT EXISTS public.enemy_reward_rules (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enemy_template_id integer NOT NULL,
    delivery_type integer NOT NULL,
    target_rule integer NOT NULL,
    game_random_table_id integer NOT NULL,
    roll_count integer NOT NULL DEFAULT 1,
    ownership_duration_seconds integer NULL,
    free_for_all_duration_seconds integer NULL,
    minimum_damage_parts_per_million integer NOT NULL DEFAULT 0,
    order_index integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT enemy_reward_rules_enemy_order_key UNIQUE (enemy_template_id, order_index),
    CONSTRAINT fk_enemy_reward_rules_enemy
        FOREIGN KEY (enemy_template_id) REFERENCES public.enemy_templates(id),
    CONSTRAINT fk_enemy_reward_rules_random_table
        FOREIGN KEY (game_random_table_id) REFERENCES public.game_random_tables(id)
);

CREATE TABLE IF NOT EXISTS public.map_enemy_spawn_groups (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    map_template_id integer NOT NULL,
    runtime_scope integer NOT NULL DEFAULT 0,
    zone_index integer NULL,
    spawn_mode integer NOT NULL DEFAULT 1,
    is_boss_spawn boolean NOT NULL DEFAULT false,
    max_alive integer NOT NULL DEFAULT 1,
    respawn_seconds integer NOT NULL DEFAULT 30,
    initial_spawn_delay_seconds integer NOT NULL DEFAULT 0,
    center_x real NOT NULL,
    center_y real NOT NULL,
    spawn_radius real NOT NULL DEFAULT 0,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT map_enemy_spawn_groups_pkey PRIMARY KEY (id),
    CONSTRAINT map_enemy_spawn_groups_code_key UNIQUE (code),
    CONSTRAINT fk_map_enemy_spawn_groups_map
        FOREIGN KEY (map_template_id) REFERENCES public.map_templates(id)
);

CREATE TABLE IF NOT EXISTS public.map_enemy_spawn_entries (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spawn_group_id integer NOT NULL,
    enemy_template_id integer NOT NULL,
    weight integer NOT NULL DEFAULT 1,
    order_index integer NOT NULL DEFAULT 0,
    CONSTRAINT map_enemy_spawn_entries_group_order_key UNIQUE (spawn_group_id, order_index),
    CONSTRAINT fk_map_enemy_spawn_entries_group
        FOREIGN KEY (spawn_group_id) REFERENCES public.map_enemy_spawn_groups(id),
    CONSTRAINT fk_map_enemy_spawn_entries_enemy
        FOREIGN KEY (enemy_template_id) REFERENCES public.enemy_templates(id)
);

CREATE TABLE IF NOT EXISTS public.map_instance_configs (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    map_template_id integer NOT NULL,
    instance_mode integer NOT NULL,
    duration_seconds integer NULL,
    idle_destroy_seconds integer NULL,
    completion_rule integer NOT NULL DEFAULT 0,
    complete_destroy_delay_seconds integer NULL,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT map_instance_configs_pkey PRIMARY KEY (id),
    CONSTRAINT map_instance_configs_code_key UNIQUE (code),
    CONSTRAINT map_instance_configs_map_template_key UNIQUE (map_template_id),
    CONSTRAINT fk_map_instance_configs_map
        FOREIGN KEY (map_template_id) REFERENCES public.map_templates(id)
);
