CREATE TABLE IF NOT EXISTS public.item_templates (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    item_type integer NOT NULL,
    rarity integer NOT NULL DEFAULT 1,
    max_stack integer NOT NULL DEFAULT 1,
    is_tradeable boolean NOT NULL DEFAULT true,
    is_droppable boolean NOT NULL DEFAULT true,
    is_destroyable boolean NOT NULL DEFAULT true,
    icon character varying(255) NULL,
    description text NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT item_templates_pkey PRIMARY KEY (id),
    CONSTRAINT item_templates_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.player_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    item_template_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    is_bound boolean NOT NULL DEFAULT false,
    acquired_at timestamp without time zone NOT NULL DEFAULT now(),
    expire_at timestamp without time zone NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT fk_player_items_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_items_item_template
        FOREIGN KEY (item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.equipment_templates (
    item_template_id integer NOT NULL,
    slot_type integer NOT NULL,
    equipment_type integer NOT NULL,
    level_requirement integer NOT NULL DEFAULT 1,
    CONSTRAINT equipment_templates_pkey PRIMARY KEY (item_template_id),
    CONSTRAINT fk_equipment_templates_item_template
        FOREIGN KEY (item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.equipment_template_stats (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_template_id integer NOT NULL,
    stat_type integer NOT NULL,
    value numeric(18, 6) NOT NULL,
    value_type integer NOT NULL,
    CONSTRAINT fk_equipment_template_stats_equipment_template
        FOREIGN KEY (equipment_template_id) REFERENCES public.equipment_templates(item_template_id)
);

CREATE TABLE IF NOT EXISTS public.player_equipments (
    player_item_id bigint NOT NULL,
    equipped_slot integer NULL,
    enhance_level integer NOT NULL DEFAULT 0,
    durability integer NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT player_equipments_pkey PRIMARY KEY (player_item_id),
    CONSTRAINT fk_player_equipments_player_item
        FOREIGN KEY (player_item_id) REFERENCES public.player_items(id)
);

CREATE TABLE IF NOT EXISTS public.player_equipment_stat_bonuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_item_id bigint NOT NULL,
    stat_type integer NOT NULL,
    value numeric(18, 6) NOT NULL,
    value_type integer NOT NULL,
    source_type integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT fk_player_equipment_stat_bonuses_player_item
        FOREIGN KEY (player_item_id) REFERENCES public.player_items(id)
);

CREATE TABLE IF NOT EXISTS public.craft_recipes (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    result_item_template_id integer NOT NULL,
    result_quantity integer NOT NULL DEFAULT 1,
    success_rate double precision NOT NULL DEFAULT 1,
    mutation_rate double precision NOT NULL DEFAULT 0,
    mutation_rate_cap double precision NOT NULL DEFAULT 0,
    cost_currency_type integer NULL,
    cost_currency_value bigint NOT NULL DEFAULT 0,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT craft_recipes_pkey PRIMARY KEY (id),
    CONSTRAINT craft_recipes_code_key UNIQUE (code),
    CONSTRAINT fk_craft_recipes_result_item_template
        FOREIGN KEY (result_item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.craft_recipe_requirements (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    craft_recipe_id integer NOT NULL,
    required_item_template_id integer NOT NULL,
    required_quantity integer NOT NULL DEFAULT 1,
    consume_mode integer NOT NULL,
    is_optional boolean NOT NULL DEFAULT false,
    mutation_bonus_rate double precision NOT NULL DEFAULT 0,
    CONSTRAINT fk_craft_recipe_requirements_recipe
        FOREIGN KEY (craft_recipe_id) REFERENCES public.craft_recipes(id),
    CONSTRAINT fk_craft_recipe_requirements_item_template
        FOREIGN KEY (required_item_template_id) REFERENCES public.item_templates(id)
);

CREATE TABLE IF NOT EXISTS public.craft_recipe_mutation_bonuses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    craft_recipe_id integer NOT NULL,
    stat_type integer NOT NULL,
    value numeric(18, 6) NOT NULL,
    value_type integer NOT NULL,
    CONSTRAINT fk_craft_recipe_mutation_bonuses_recipe
        FOREIGN KEY (craft_recipe_id) REFERENCES public.craft_recipes(id)
);

CREATE TABLE IF NOT EXISTS public.martial_art_book_templates (
    item_template_id integer NOT NULL,
    martial_art_id integer NOT NULL,
    CONSTRAINT martial_art_book_templates_pkey PRIMARY KEY (item_template_id),
    CONSTRAINT fk_martial_art_book_templates_item_template
        FOREIGN KEY (item_template_id) REFERENCES public.item_templates(id),
    CONSTRAINT fk_martial_art_book_templates_martial_art
        FOREIGN KEY (martial_art_id) REFERENCES public.martial_arts(id)
);
