CREATE TABLE IF NOT EXISTS public.martial_arts (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    quality integer NOT NULL DEFAULT 1,
    category character varying(50) NULL,
    description text NULL,
    qi_absorption_rate numeric(10,4) NOT NULL DEFAULT 1.0,
    max_stage integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT martial_arts_pkey PRIMARY KEY (id),
    CONSTRAINT martial_arts_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.martial_art_stages (
    id integer NOT NULL,
    martial_art_id integer NOT NULL,
    stage_level integer NOT NULL,
    exp_required bigint NOT NULL,
    is_bottleneck boolean NOT NULL DEFAULT false,
    breakthrough_base_rate double precision NULL,
    breakthrough_exp_penalty bigint NOT NULL DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT martial_art_stages_pkey PRIMARY KEY (id),
    CONSTRAINT martial_art_stages_martial_art_stage_key UNIQUE (martial_art_id, stage_level),
    CONSTRAINT fk_martial_art_stages_martial_art
        FOREIGN KEY (martial_art_id) REFERENCES public.martial_arts(id)
);

CREATE TABLE IF NOT EXISTS public.martial_art_stage_stat_bonuses (
    id integer NOT NULL,
    martial_art_stage_id integer NOT NULL,
    stat_type integer NOT NULL,
    value numeric(18, 6) NOT NULL,
    value_type integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT martial_art_stage_stat_bonuses_pkey PRIMARY KEY (id),
    CONSTRAINT fk_martial_art_stage_stat_bonuses_stage
        FOREIGN KEY (martial_art_stage_id) REFERENCES public.martial_art_stages(id)
);

CREATE TABLE IF NOT EXISTS public.skills (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    skill_type integer NOT NULL,
    target_type integer NOT NULL,
    cast_range numeric(10, 4) NOT NULL DEFAULT 1.0,
    cooldown_ms integer NOT NULL DEFAULT 0,
    description text NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT skills_pkey PRIMARY KEY (id),
    CONSTRAINT skills_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.skill_effects (
    id integer NOT NULL,
    skill_id integer NOT NULL,
    effect_type integer NOT NULL,
    order_index integer NOT NULL DEFAULT 0,
    formula_type integer NULL,
    value_type integer NULL,
    base_value numeric(18, 6) NULL,
    ratio_value numeric(18, 6) NULL,
    extra_value numeric(18, 6) NULL,
    chance_value numeric(18, 6) NULL,
    duration_ms integer NULL,
    stat_type integer NULL,
    resource_type integer NULL,
    target_scope integer NULL,
    trigger_timing integer NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT skill_effects_pkey PRIMARY KEY (id),
    CONSTRAINT skill_effects_skill_order_key UNIQUE (skill_id, order_index),
    CONSTRAINT fk_skill_effects_skill
        FOREIGN KEY (skill_id) REFERENCES public.skills(id)
);

CREATE TABLE IF NOT EXISTS public.martial_art_skills (
    id integer NOT NULL,
    martial_art_id integer NOT NULL,
    skill_id integer NOT NULL,
    unlock_stage integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT martial_art_skills_pkey PRIMARY KEY (id),
    CONSTRAINT martial_art_skills_martial_art_skill_key UNIQUE (martial_art_id, skill_id),
    CONSTRAINT fk_martial_art_skills_martial_art
        FOREIGN KEY (martial_art_id) REFERENCES public.martial_arts(id),
    CONSTRAINT fk_martial_art_skills_skill
        FOREIGN KEY (skill_id) REFERENCES public.skills(id)
);

CREATE TABLE IF NOT EXISTS public.martial_art_skill_scalings (
    id integer NOT NULL,
    martial_art_skill_id integer NOT NULL,
    skill_effect_id integer NULL,
    scaling_target integer NOT NULL,
    base_value numeric(18, 6) NOT NULL DEFAULT 0,
    per_stage_value numeric(18, 6) NOT NULL DEFAULT 0,
    value_type integer NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT martial_art_skill_scalings_pkey PRIMARY KEY (id),
    CONSTRAINT fk_martial_art_skill_scalings_martial_art_skill
        FOREIGN KEY (martial_art_skill_id) REFERENCES public.martial_art_skills(id),
    CONSTRAINT fk_martial_art_skill_scalings_skill_effect
        FOREIGN KEY (skill_effect_id) REFERENCES public.skill_effects(id)
);

CREATE TABLE IF NOT EXISTS public.player_martial_arts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    martial_art_id integer NOT NULL,
    current_stage integer NOT NULL DEFAULT 1,
    current_exp bigint NOT NULL DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT player_martial_arts_player_martial_art_key UNIQUE (player_id, martial_art_id),
    CONSTRAINT fk_player_martial_arts_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_martial_arts_martial_art
        FOREIGN KEY (martial_art_id) REFERENCES public.martial_arts(id)
);

CREATE TABLE IF NOT EXISTS public.player_skills (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    skill_id integer NOT NULL,
    source_martial_art_id integer NOT NULL,
    source_martial_art_skill_id integer NOT NULL,
    unlocked_at timestamp without time zone DEFAULT now(),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT player_skills_player_source_skill_key UNIQUE (player_id, source_martial_art_skill_id),
    CONSTRAINT fk_player_skills_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_skills_skill
        FOREIGN KEY (skill_id) REFERENCES public.skills(id),
    CONSTRAINT fk_player_skills_source_martial_art
        FOREIGN KEY (source_martial_art_id) REFERENCES public.martial_arts(id),
    CONSTRAINT fk_player_skills_source_martial_art_skill
        FOREIGN KEY (source_martial_art_skill_id) REFERENCES public.martial_art_skills(id)
);

CREATE TABLE IF NOT EXISTS public.player_skill_loadouts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL,
    slot_index integer NOT NULL,
    player_skill_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT player_skill_loadouts_player_slot_key UNIQUE (player_id, slot_index),
    CONSTRAINT fk_player_skill_loadouts_player
        FOREIGN KEY (player_id) REFERENCES public.characters(id),
    CONSTRAINT fk_player_skill_loadouts_player_skill
        FOREIGN KEY (player_skill_id) REFERENCES public.player_skills(id)
);
