BEGIN;

CREATE TABLE IF NOT EXISTS public.map_spawn_points (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_template_id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    spawn_category integer NOT NULL DEFAULT 4,
    pos_x real NOT NULL,
    pos_y real NOT NULL,
    facing_degrees real NULL,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT map_spawn_points_map_code_key UNIQUE (map_template_id, code),
    CONSTRAINT map_spawn_points_map_id_id_key UNIQUE (map_template_id, id),
    CONSTRAINT fk_map_spawn_points_map
        FOREIGN KEY (map_template_id) REFERENCES public.map_templates(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_map_spawn_points_map_template_id
    ON public.map_spawn_points (map_template_id);

CREATE TABLE IF NOT EXISTS public.map_portals (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_map_template_id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    source_x real NOT NULL,
    source_y real NOT NULL,
    interaction_radius real NOT NULL DEFAULT 24,
    target_map_template_id integer NOT NULL,
    target_spawn_point_id integer NOT NULL,
    is_enabled boolean NOT NULL DEFAULT true,
    order_index integer NOT NULL DEFAULT 0,
    description text NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT map_portals_source_code_key UNIQUE (source_map_template_id, code),
    CONSTRAINT fk_map_portals_source_map
        FOREIGN KEY (source_map_template_id) REFERENCES public.map_templates(id) ON DELETE CASCADE,
    CONSTRAINT fk_map_portals_target_map
        FOREIGN KEY (target_map_template_id) REFERENCES public.map_templates(id) ON DELETE RESTRICT,
    CONSTRAINT fk_map_portals_target_spawn
        FOREIGN KEY (target_map_template_id, target_spawn_point_id)
            REFERENCES public.map_spawn_points(map_template_id, id)
            ON DELETE RESTRICT,
    CONSTRAINT ck_map_portals_interaction_radius_positive
        CHECK (interaction_radius > 0)
);

CREATE INDEX IF NOT EXISTS idx_map_portals_source_map_template_id
    ON public.map_portals (source_map_template_id);

CREATE INDEX IF NOT EXISTS idx_map_portals_target_map_template_id
    ON public.map_portals (target_map_template_id);

INSERT INTO public.map_spawn_points (
    map_template_id,
    code,
    name,
    spawn_category,
    pos_x,
    pos_y,
    description
)
SELECT
    map_template.id,
    'default_entry',
    'Default Entry',
    4,
    map_template.default_spawn_x,
    map_template.default_spawn_y,
    'Generated automatically from map_templates.default_spawn_x/default_spawn_y.'
FROM public.map_templates map_template
ON CONFLICT (map_template_id, code) DO UPDATE
SET
    name = EXCLUDED.name,
    spawn_category = EXCLUDED.spawn_category,
    pos_x = EXCLUDED.pos_x,
    pos_y = EXCLUDED.pos_y,
    description = EXCLUDED.description;

COMMIT;
