using System.Data;
using System.Globalization;
using System.Text;
using Npgsql;

namespace AdminDesignerTool;

internal sealed class TableEditorControl : UserControl
{
    private readonly Label _titleLabel;
    private readonly Label _descriptionLabel;
    private readonly TextBox _helpTextBox;
    private readonly Button _refreshButton;
    private readonly Button _addButton;
    private readonly Button _duplicateButton;
    private readonly Button _deleteButton;
    private readonly Button _saveButton;
    private readonly TextBox _filterTextBox;
    private readonly Button _clearFilterButton;
    private readonly ComboBox _fieldHelpComboBox;
    private readonly TextBox _fieldHelpTextBox;
    private readonly DataGridView _grid;
    private readonly Label _statusLabel;

    private readonly string _connectionString;
    private AdminTableLoadRequest? _request;
    private DataTable? _table;
    private NpgsqlDataAdapter? _adapter;
    private Dictionary<string, IReadOnlyList<LookupOption>> _lookupOptionsByColumn = new(StringComparer.OrdinalIgnoreCase);
    private readonly HashSet<DataRow> _autoGeneratedCodeRows = [];
    private bool _isReloadingData;
    private AdminDependencyEvaluation _dependencyEvaluation = new(true, Array.Empty<string>());

    public event EventHandler? SelectedRowChanged;

    public string ConnectionString => _connectionString;

    public TableEditorControl(string connectionString, bool showResourceHelpBox = true)
    {
        _connectionString = connectionString;

        Dock = DockStyle.Fill;
        Padding = new Padding(12);

        _titleLabel = new Label
        {
            Dock = DockStyle.Top,
            Height = 28,
            Font = new Font("Segoe UI", 14f, FontStyle.Bold),
            Text = "Chon mot resource ben trai"
        };

        _descriptionLabel = new Label
        {
            Dock = DockStyle.Top,
            Height = 24,
            Font = new Font("Segoe UI", 8.75f, FontStyle.Regular),
            ForeColor = Color.DimGray,
            AutoEllipsis = true,
            Text = "Tool nay cho phep them/sua/xoa truc tiep cac bang template trong DB."
        };

        _helpTextBox = new TextBox
        {
            Dock = DockStyle.Top,
            Height = 82,
            Multiline = true,
            ReadOnly = true,
            ScrollBars = ScrollBars.Vertical,
            BackColor = Color.WhiteSmoke,
            Font = new Font("Segoe UI", 9f, FontStyle.Regular),
            Text = "Huong dan resource se hien o day."
        };

        var buttonPanel = new FlowLayoutPanel
        {
            Dock = DockStyle.Top,
            Height = 42,
            AutoSize = false,
            FlowDirection = FlowDirection.LeftToRight,
            WrapContents = false
        };

        _refreshButton = new Button { Text = "Tai Lai", AutoSize = true };
        _addButton = new Button { Text = "Them Dong", AutoSize = true };
        _duplicateButton = new Button { Text = "Nhan Ban Dong", AutoSize = true };
        _deleteButton = new Button { Text = "Xoa Dong", AutoSize = true };
        _saveButton = new Button { Text = "Luu Thay Doi", AutoSize = true };

        _refreshButton.Click += async (_, _) => await ReloadAsync();
        _addButton.Click += (_, _) => AddRow();
        _duplicateButton.Click += (_, _) => DuplicateSelectedRow();
        _deleteButton.Click += (_, _) => DeleteSelectedRows();
        _saveButton.Click += async (_, _) => await SaveChangesAsync();

        buttonPanel.Controls.AddRange([_refreshButton, _addButton, _duplicateButton, _deleteButton, _saveButton]);

        var filterPanel = new FlowLayoutPanel
        {
            Dock = DockStyle.Top,
            Height = 40,
            AutoSize = false,
            FlowDirection = FlowDirection.LeftToRight,
            WrapContents = false
        };

        filterPanel.Controls.Add(new Label
        {
            AutoSize = true,
            Text = "Loc nhanh:",
            Margin = new Padding(3, 9, 3, 0)
        });

        _filterTextBox = new TextBox
        {
            Width = 280
        };
        _filterTextBox.TextChanged += (_, _) => ApplyFilter();

        _clearFilterButton = new Button
        {
            Text = "Xoa Loc",
            AutoSize = true
        };
        _clearFilterButton.Click += (_, _) =>
        {
            _filterTextBox.Text = string.Empty;
            ApplyFilter();
        };

        filterPanel.Controls.Add(_filterTextBox);
        filterPanel.Controls.Add(_clearFilterButton);

        var fieldHelpPanel = new TableLayoutPanel
        {
            Dock = DockStyle.Top,
            Height = 76,
            ColumnCount = 2,
            RowCount = 2,
            Padding = new Padding(0, 2, 0, 0)
        };
        fieldHelpPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180f));
        fieldHelpPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
        fieldHelpPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 28f));
        fieldHelpPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));

        fieldHelpPanel.Controls.Add(new Label
        {
            Text = "Trợ giúp trường:",
            Dock = DockStyle.Fill,
            TextAlign = ContentAlignment.MiddleLeft
        }, 0, 0);

        _fieldHelpComboBox = new ComboBox
        {
            Dock = DockStyle.Fill,
            DropDownStyle = ComboBoxStyle.DropDownList
        };
        _fieldHelpComboBox.SelectedIndexChanged += (_, _) => UpdateFieldHelpFromSelection();
        fieldHelpPanel.Controls.Add(_fieldHelpComboBox, 1, 0);

        fieldHelpPanel.Controls.Add(new Label
        {
            Text = "Mô tả trường:",
            Dock = DockStyle.Fill,
            TextAlign = ContentAlignment.TopLeft
        }, 0, 1);

        _fieldHelpTextBox = new TextBox
        {
            Dock = DockStyle.Fill,
            Multiline = true,
            ReadOnly = true,
            ScrollBars = ScrollBars.Vertical,
            BackColor = Color.WhiteSmoke,
            Font = new Font("Segoe UI", 9f, FontStyle.Regular)
        };
        fieldHelpPanel.Controls.Add(_fieldHelpTextBox, 1, 1);

        _grid = new DataGridView
        {
            Dock = DockStyle.Fill,
            AllowUserToAddRows = false,
            AllowUserToDeleteRows = false,
            AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells,
            BackgroundColor = Color.White,
            BorderStyle = BorderStyle.FixedSingle,
            SelectionMode = DataGridViewSelectionMode.FullRowSelect,
            MultiSelect = true
        };
        _grid.EnableHeadersVisualStyles = false;
        _grid.SelectionChanged += (_, _) => SelectedRowChanged?.Invoke(this, EventArgs.Empty);
        _grid.DataError += (_, _) => { };
        _grid.CellParsing += GridOnCellParsing;
        _grid.CellFormatting += GridOnCellFormatting;
        _grid.CellEndEdit += GridOnCellEndEdit;
        _grid.CurrentCellDirtyStateChanged += GridOnCurrentCellDirtyStateChanged;
        _grid.CellEnter += GridOnCellEnter;
        _grid.ColumnHeaderMouseClick += GridOnColumnHeaderMouseClick;

        _statusLabel = new Label
        {
            Dock = DockStyle.Bottom,
            Height = 28,
            ForeColor = Color.DimGray,
            Text = "San sang."
        };

        Controls.Add(_grid);
        Controls.Add(_statusLabel);
        Controls.Add(fieldHelpPanel);
        Controls.Add(filterPanel);
        Controls.Add(buttonPanel);
        if (showResourceHelpBox)
            Controls.Add(_helpTextBox);
        Controls.Add(_descriptionLabel);
        Controls.Add(_titleLabel);
    }

    public async Task LoadResourceAsync(AdminResourceDefinition resource)
    {
        await LoadRequestAsync(AdminTableLoadRequest.ForResource(resource));
    }

    public async Task LoadRequestAsync(AdminTableLoadRequest request)
    {
        _request = request;
        _titleLabel.Text = request.EffectiveTitle;
        _descriptionLabel.Text = request.EffectiveDescription;
        _helpTextBox.Text = request.EffectiveHelpText;
        await ReloadAsync();
    }

    public bool TryGetSelectedInt(string columnName, out int value)
    {
        value = default;
        if (_grid.CurrentRow is not DataGridViewRow currentRow || !currentRow.Visible)
            return false;

        if (currentRow.DataBoundItem is not DataRowView rowView)
            return false;

        if (!_table?.Columns.Contains(columnName) ?? true)
            return false;

        if (!ReferenceEquals(rowView.Row.Table, _table) || rowView.Row.RowState == DataRowState.Deleted)
            return false;

        var rawValue = rowView.Row[columnName];
        if (rawValue == DBNull.Value)
            return false;

        value = Convert.ToInt32(rawValue);
        return true;
    }

    private async Task ReloadAsync()
    {
        if (_request is null)
            return;

        if (_request.Resource.TableName == "monster_templates")
        {
            _grid.DataSource = null;
            _statusLabel.Text = "Schema boss/drop chua ton tai. Resource nay la cho mo rong sau.";
            return;
        }

        try
        {
            SetBusy(true, "Dang tai du lieu...");
            _isReloadingData = true;
            _grid.DataSource = null;
            _grid.Columns.Clear();
            var result = await Task.Run(() => LoadTable(_request), default);
            DisposeAdapter();
            _adapter = result.Adapter;
            _table = result.Table;
            _autoGeneratedCodeRows.Clear();
            _lookupOptionsByColumn = await LoadLookupOptionsAsync(_request, _table);
            _dependencyEvaluation = await AdminDependencyCatalog.EvaluateAsync(_connectionString, _request);

            BuildGridColumns(_request, _table);
            _grid.DataSource = _table.DefaultView;
            PopulateFieldHelpOptions(_request, _table);
            SelectFirstRow();
            ApplyFilter();
        }
        catch (Exception ex)
        {
            _grid.DataSource = null;
            _statusLabel.Text = $"Tai du lieu that bai: {ex.Message}";
        }
        finally
        {
            _isReloadingData = false;
            ApplyDependencyState();
            SetBusy(false, null);
        }
    }

    private async Task SaveChangesAsync()
    {
        if (_adapter is null || _table is null || _request is null)
            return;

        try
        {
            if (!_isReloadingData)
                _grid.EndEdit();

            ApplyAuditTimestampValues();
            var validationIssues = ValidatePendingChanges();
            if (validationIssues.Count > 0)
            {
                var firstIssue = validationIssues[0];
                SelectValidationIssue(firstIssue);
                _statusLabel.Text = $"Con {validationIssues.Count} loi can sua truoc khi luu.";
                MessageBox.Show(
                    BuildValidationMessage(validationIssues),
                    "Du lieu chua hop le",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Warning);
                _grid.Refresh();
                return;
            }

            SetBusy(true, "Dang luu thay doi...");
            await Task.Run(() =>
            {
                using var builder = new NpgsqlCommandBuilder(_adapter)
                {
                    QuotePrefix = "\"",
                    QuoteSuffix = "\""
                };
                _adapter.InsertCommand = builder.GetInsertCommand();
                _adapter.UpdateCommand = builder.GetUpdateCommand();
                _adapter.DeleteCommand = builder.GetDeleteCommand();
                _adapter.Update(_table);
            });

            _statusLabel.Text = $"Da luu thay doi cho {_request.Resource.TableName}.";
            await ReloadAsync();
        }
        catch (Exception ex)
        {
            _statusLabel.Text = $"Luu that bai: {ex.Message}";
            MessageBox.Show(
                $"Khong the luu thay doi cho {_request.Resource.TableName}.\r\n\r\n{ex.Message}",
                "Save Failed",
                MessageBoxButtons.OK,
                MessageBoxIcon.Error);
        }
        finally
        {
            SetBusy(false, null);
        }
    }

    private void AddRow()
    {
        if (_table is null || !_dependencyEvaluation.CanAddRow)
            return;

        var defaultView = _table.DefaultView;
        if (!string.IsNullOrEmpty(defaultView?.RowFilter))
            defaultView.RowFilter = string.Empty;

        var row = _table.NewRow();
        ApplyDefaultValues(row);
        ApplyAuditTimestampValues(row, isNewRow: true);
        MarkAutoGeneratedCodeIfNeeded(row);

        if (_request?.NewRowDefaults is not null)
        {
            foreach (var pair in _request.NewRowDefaults)
            {
                if (!_table.Columns.Contains(pair.Key))
                    continue;

                row[pair.Key] = pair.Value ?? DBNull.Value;
            }
        }

        ApplyAuditTimestampValues(row, isNewRow: true);
        TryUpdateCodeFromName(row);

        _table.Rows.Add(row);
        SelectRow(row);
        _grid.Refresh();
        _statusLabel.Text = "Da them mot dong moi. Nhap du lieu roi bam Luu Thay Doi.";
    }

    private void DuplicateSelectedRow()
    {
        if (_table is null || _grid.CurrentRow?.DataBoundItem is not DataRowView sourceView)
            return;

        var newRow = _table.NewRow();
        foreach (DataColumn column in _table.Columns)
        {
            if (column.AutoIncrement)
                continue;

            if (sourceView.Row.RowState == DataRowState.Deleted)
                continue;

            newRow[column.ColumnName] = sourceView.Row[column.ColumnName];
        }

        foreach (DataColumn column in _table.Columns)
        {
            if (column.AutoIncrement || column.ReadOnly)
                continue;

            if (TryGetSuggestedUniqueValue(column, out var uniqueValue))
                newRow[column.ColumnName] = uniqueValue;
        }

        MarkAutoGeneratedCodeIfNeeded(newRow);
        TryUpdateCodeFromName(newRow);
        _table.Rows.Add(newRow);
        SelectRow(newRow);
        _grid.Refresh();
        _statusLabel.Text = "Da nhan ban dong hien tai. Kiem tra lai id/code truoc khi luu.";
    }

    private void DeleteSelectedRows()
    {
        if (_table is null || _grid.SelectedRows.Count == 0)
            return;

        foreach (DataGridViewRow selectedRow in _grid.SelectedRows)
        {
            if (selectedRow.DataBoundItem is not DataRowView rowView)
                continue;

            _autoGeneratedCodeRows.Remove(rowView.Row);
            rowView.Row.Delete();
        }

        _grid.Refresh();
        _statusLabel.Text = "Da danh dau xoa cac dong duoc chon. Bam Luu Thay Doi de ap dung.";
    }

    private void SetBusy(bool isBusy, string? statusText)
    {
        _refreshButton.Enabled = !isBusy;
        _addButton.Enabled = !isBusy && _dependencyEvaluation.CanAddRow;
        _duplicateButton.Enabled = !isBusy;
        _deleteButton.Enabled = !isBusy;
        _saveButton.Enabled = !isBusy;
        _filterTextBox.Enabled = !isBusy;
        _clearFilterButton.Enabled = !isBusy;
        _grid.Enabled = !isBusy;
        if (!string.IsNullOrWhiteSpace(statusText))
            _statusLabel.Text = statusText;
    }

    private void ApplyDependencyState()
    {
        _addButton.Enabled = _dependencyEvaluation.CanAddRow;
        if (_dependencyEvaluation.CanAddRow)
        {
            _addButton.Text = "Them Dong";
            return;
        }

        _addButton.Text = "Them Dong (Bi Khoa)";
        if (_request is not null)
        {
            var dependencyText = string.Join("\r\n", _dependencyEvaluation.MissingMessages);
            _helpTextBox.Text = $"{_request.EffectiveHelpText}\r\n\r\nChua the them dong moi:\r\n{dependencyText}";
            _statusLabel.Text = _dependencyEvaluation.MissingMessages[0];
        }
    }

    private void PopulateFieldHelpOptions(AdminTableLoadRequest request, DataTable table)
    {
        _fieldHelpComboBox.BeginUpdate();
        try
        {
            _fieldHelpComboBox.Items.Clear();
            foreach (DataColumn column in table.Columns)
            {
                var binding = AdminColumnBindingCatalog.Find(request.Resource.TableName, column.ColumnName);
                var displayName = binding?.HeaderText ?? AdminColumnBindingCatalog.ToHeaderText(column.ColumnName);
                _fieldHelpComboBox.Items.Add(new FieldHelpOption(column.ColumnName, displayName));
            }

            if (_fieldHelpComboBox.Items.Count > 0)
                _fieldHelpComboBox.SelectedIndex = 0;
            else
                _fieldHelpTextBox.Text = "Bảng hiện tại không có trường nào để hiển thị mô tả.";
        }
        finally
        {
            _fieldHelpComboBox.EndUpdate();
        }
    }

    private void UpdateFieldHelpFromSelection()
    {
        if (_request is null || _table is null || _fieldHelpComboBox.SelectedItem is not FieldHelpOption option)
        {
            _fieldHelpTextBox.Text = string.Empty;
            UpdateFieldHelpHighlight(null);
            return;
        }

        if (_table.Columns[option.ColumnName] is not DataColumn column)
        {
            _fieldHelpTextBox.Text = string.Empty;
            UpdateFieldHelpHighlight(null);
            return;
        }

        var binding = AdminColumnBindingCatalog.Find(_request.Resource.TableName, option.ColumnName);
        _fieldHelpTextBox.Text = AdminFieldHelpCatalog.BuildHelpText(_request.Resource, column, binding);
        UpdateFieldHelpHighlight(option.ColumnName);
    }

    private void SelectFieldHelp(string columnName)
    {
        for (var index = 0; index < _fieldHelpComboBox.Items.Count; index++)
        {
            if (_fieldHelpComboBox.Items[index] is not FieldHelpOption option)
                continue;

            if (!string.Equals(option.ColumnName, columnName, StringComparison.OrdinalIgnoreCase))
                continue;

            _fieldHelpComboBox.SelectedIndex = index;
            return;
        }
    }

    private void UpdateFieldHelpHighlight(string? selectedColumnName)
    {
        foreach (DataGridViewColumn column in _grid.Columns)
        {
            var isSelected = !string.IsNullOrWhiteSpace(selectedColumnName) &&
                             string.Equals(column.DataPropertyName, selectedColumnName, StringComparison.OrdinalIgnoreCase);

            column.HeaderCell.Style.BackColor = isSelected ? Color.FromArgb(255, 244, 204) : Color.WhiteSmoke;
            column.HeaderCell.Style.ForeColor = Color.Black;
            column.HeaderCell.Style.Font = new Font(_grid.Font, isSelected ? FontStyle.Bold : FontStyle.Regular);
        }

        _grid.Invalidate();
    }

    private (NpgsqlDataAdapter Adapter, DataTable Table) LoadTable(AdminTableLoadRequest request)
    {
        var connection = new NpgsqlConnection(_connectionString);
        var command = new NpgsqlCommand(request.EffectiveSelectSql, connection);
        var adapter = new NpgsqlDataAdapter(command);
        adapter.MissingSchemaAction = MissingSchemaAction.AddWithKey;
        var table = new DataTable(request.Resource.TableName);
        adapter.FillSchema(table, SchemaType.Source);
        adapter.Fill(table);
        return (adapter, table);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            DisposeAdapter();

        base.Dispose(disposing);
    }

    private void DisposeAdapter()
    {
        if (_adapter is null)
            return;

        DisposeCommand(_adapter.SelectCommand);
        DisposeCommand(_adapter.InsertCommand);
        DisposeCommand(_adapter.UpdateCommand);
        DisposeCommand(_adapter.DeleteCommand);
        _adapter.Dispose();
        _adapter = null;
    }

    private static void DisposeCommand(NpgsqlCommand? command)
    {
        if (command is null)
            return;

        var connection = command.Connection;
        command.Dispose();
        connection?.Dispose();
    }

    private async Task<Dictionary<string, IReadOnlyList<LookupOption>>> LoadLookupOptionsAsync(
        AdminTableLoadRequest request,
        DataTable table)
    {
        var result = new Dictionary<string, IReadOnlyList<LookupOption>>(StringComparer.OrdinalIgnoreCase);
        foreach (DataColumn column in table.Columns)
        {
            var binding = AdminColumnBindingCatalog.Find(request.Resource.TableName, column.ColumnName);
            if (binding is null)
                continue;

            result[column.ColumnName] = await AdminColumnBindingCatalog.LoadOptionsAsync(
                _connectionString,
                binding,
                column.AllowDBNull);
        }

        return result;
    }

    private void ApplyDefaultValues(DataRow row)
    {
        if (_table is null)
            return;

        foreach (DataColumn column in _table.Columns)
        {
            if (column.AutoIncrement || column.ReadOnly)
                continue;

            if (TryGetSuggestedUniqueValue(column, out var uniqueValue))
            {
                row[column.ColumnName] = uniqueValue;
                continue;
            }

            if (!column.AllowDBNull)
            {
                row[column.ColumnName] = GetDefaultValue(column);
                continue;
            }

            if (_lookupOptionsByColumn.TryGetValue(column.ColumnName, out var lookupOptions))
            {
                var firstNonNull = lookupOptions.FirstOrDefault(x => x.Value is not null);
                if (firstNonNull?.Value is not null)
                    row[column.ColumnName] = firstNonNull.Value;
            }
        }
    }

    private void ApplyAuditTimestampValues()
    {
        if (_table is null)
            return;

        foreach (var row in _table.Rows.Cast<DataRow>().Where(static row => row.RowState != DataRowState.Deleted))
            ApplyAuditTimestampValues(row, row.RowState == DataRowState.Added);
    }

    private static void ApplyAuditTimestampValues(DataRow row, bool isNewRow)
    {
        var utcNow = DateTime.UtcNow;
        SetAuditColumnValue(row, "created_at", isNewRow, utcNow);
        SetAuditColumnValue(row, "updated_at", true, utcNow);
    }

    private static void SetAuditColumnValue(DataRow row, string columnName, bool shouldSet, DateTime utcNow)
    {
        if (!shouldSet || !row.Table.Columns.Contains(columnName))
            return;

        if (row.Table.Columns[columnName] is not DataColumn column)
            return;

        if (column.ReadOnly)
            return;

        var currentValue = row[column];
        var isMissing = currentValue == DBNull.Value ||
                        currentValue is null ||
                        currentValue is DateTime dateTime && dateTime == default;

        if (string.Equals(columnName, "created_at", StringComparison.OrdinalIgnoreCase) && !isMissing)
            return;

        row[column] = utcNow;
    }

    private void MarkAutoGeneratedCodeIfNeeded(DataRow row)
    {
        if (!_table?.Columns.Contains("code") ?? true)
            return;

        var rawCode = row["code"];
        if (rawCode == DBNull.Value)
            return;

        var code = Convert.ToString(rawCode);
        if (string.IsNullOrWhiteSpace(code))
            return;

        if (code.StartsWith("new_code", StringComparison.OrdinalIgnoreCase))
            _autoGeneratedCodeRows.Add(row);
    }

    private bool TryGetSuggestedUniqueValue(DataColumn column, out object value)
    {
        value = DBNull.Value;
        if (_table is null || !IsUniqueColumn(column))
            return false;

        var type = Nullable.GetUnderlyingType(column.DataType) ?? column.DataType;
        if (type == typeof(int))
        {
            value = GetNextNumericValue(column, 1, raw => Convert.ToInt32(raw));
            return true;
        }

        if (type == typeof(long))
        {
            value = GetNextNumericValue(column, 1L, raw => Convert.ToInt64(raw));
            return true;
        }

        if (type == typeof(short))
        {
            value = GetNextNumericValue(column, (short)1, raw => Convert.ToInt16(raw));
            return true;
        }

        if (type == typeof(string))
        {
            value = GetNextUniqueStringValue(column);
            return true;
        }

        if (type == typeof(Guid))
        {
            value = Guid.NewGuid();
            return true;
        }

        return false;
    }

    private static bool IsUniqueColumn(DataColumn column)
    {
        if (column.Unique)
            return true;

        return column.Table?.PrimaryKey.Any(x => x.ColumnName == column.ColumnName) == true;
    }

    private T GetNextNumericValue<T>(DataColumn column, T seed, Func<object, T> converter)
        where T : struct, IComparable<T>
    {
        if (_table is null)
            return seed;

        var values = _table.Rows
            .Cast<DataRow>()
            .Where(row => row.RowState != DataRowState.Deleted && row[column.ColumnName] != DBNull.Value)
            .Select(row => converter(row[column.ColumnName]))
            .ToList();

        if (values.Count == 0)
            return seed;

        dynamic max = values.Max();
        return (T)(max + 1);
    }

    private string GetNextUniqueStringValue(DataColumn column)
    {
        if (_table is null)
            return $"new_{column.ColumnName}";

        var existingValues = _table.Rows
            .Cast<DataRow>()
            .Where(row => row.RowState != DataRowState.Deleted && row[column.ColumnName] != DBNull.Value)
            .Select(row => Convert.ToString(row[column.ColumnName]) ?? string.Empty)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        var prefix = $"new_{column.ColumnName}";
        if (!existingValues.Contains(prefix))
            return prefix;

        var index = 1;
        while (existingValues.Contains($"{prefix}_{index}"))
            index++;

        return $"{prefix}_{index}";
    }

    private object GetDefaultValue(DataColumn column)
    {
        if (_lookupOptionsByColumn.TryGetValue(column.ColumnName, out var lookupOptions))
        {
            var firstNonNull = lookupOptions.FirstOrDefault(x => x.Value is not null);
            if (firstNonNull?.Value is not null)
                return firstNonNull.Value;
        }

        var type = Nullable.GetUnderlyingType(column.DataType) ?? column.DataType;
        if (type == typeof(string))
            return string.Empty;
        if (type == typeof(bool))
            return false;
        if (type == typeof(DateTime))
            return DateTime.Now;
        if (type == typeof(Guid))
            return Guid.Empty;
        if (type == typeof(short))
            return (short)0;
        if (type == typeof(int))
            return 0;
        if (type == typeof(long))
            return 0L;
        if (type == typeof(decimal))
            return 0m;
        if (type == typeof(double))
            return 0d;
        if (type == typeof(float))
            return 0f;
        if (type == typeof(byte))
            return (byte)0;

        return DBNull.Value;
    }

    private List<ValidationIssue> ValidatePendingChanges()
    {
        var issues = new List<ValidationIssue>();
        if (_table is null)
            return issues;

        var activeRows = _table.Rows
            .Cast<DataRow>()
            .Where(row => row.RowState != DataRowState.Deleted)
            .ToArray();

        foreach (var row in activeRows)
        {
            foreach (DataColumn column in _table.Columns)
            {
                if (column.ReadOnly || column.AutoIncrement)
                    continue;

                if (IsMissingRequiredValue(row, column))
                {
                    issues.Add(new ValidationIssue(row, column.ColumnName, $"Cot '{column.ColumnName}' la bat buoc."));
                }
            }
        }

        foreach (Constraint constraint in _table.Constraints)
        {
            if (constraint is not UniqueConstraint uniqueConstraint)
                continue;

            var duplicateGroups = activeRows
                .Where(row => uniqueConstraint.Columns.All(column => !IsNullLike(row[column])))
                .GroupBy(row => BuildConstraintKey(row, uniqueConstraint.Columns))
                .Where(group => group.Count() > 1);

            foreach (var group in duplicateGroups)
            {
                foreach (var row in group)
                {
                    foreach (var column in uniqueConstraint.Columns)
                    {
                        issues.Add(new ValidationIssue(
                            row,
                            column.ColumnName,
                            $"Gia tri bi trung theo rang buoc unique: {string.Join(", ", uniqueConstraint.Columns.Select(x => x.ColumnName))}."));
                    }
                }
            }
        }

        return issues
            .GroupBy(issue => (issue.Row, issue.ColumnName, issue.Message))
            .Select(group => group.First())
            .ToList();
    }

    private bool IsMissingRequiredValue(DataRow row, DataColumn column)
    {
        if (column.AllowDBNull)
            return false;

        var value = row[column];
        if (IsNullLike(value))
            return true;

        return column.DataType == typeof(string) && string.IsNullOrWhiteSpace(Convert.ToString(value));
    }

    private static bool IsNullLike(object? value)
    {
        return value is null or DBNull;
    }

    private static string BuildConstraintKey(DataRow row, DataColumn[] columns)
    {
        return string.Join("||", columns.Select(column => Convert.ToString(row[column], CultureInfo.InvariantCulture) ?? string.Empty));
    }

    private void SelectValidationIssue(ValidationIssue issue)
    {
        foreach (DataGridViewRow gridRow in _grid.Rows)
        {
            if (gridRow.DataBoundItem is not DataRowView rowView || !ReferenceEquals(rowView.Row, issue.Row))
                continue;

            if (!_grid.Columns.Contains(issue.ColumnName))
                return;

            _grid.ClearSelection();
            gridRow.Selected = true;
            _grid.CurrentCell = gridRow.Cells[issue.ColumnName];
            TryScrollRowIntoView(gridRow);
            return;
        }
    }

    private string BuildValidationMessage(IReadOnlyList<ValidationIssue> issues)
    {
        var lines = issues
            .Take(12)
            .Select((issue, index) => $"{index + 1}. {issue.Message} (cot: {issue.ColumnName})")
            .ToList();

        if (issues.Count > lines.Count)
            lines.Add($"... va {issues.Count - lines.Count} loi khac.");

        return $"Khong the luu vi du lieu chua hop le.\r\n\r\n{string.Join("\r\n", lines)}";
    }

    private void GridOnCurrentCellDirtyStateChanged(object? sender, EventArgs e)
    {
        if (_isReloadingData)
            return;

        if (_grid.IsCurrentCellDirty)
        {
            var currentCell = _grid.CurrentCell;
            if (currentCell is DataGridViewCheckBoxCell or DataGridViewComboBoxCell)
                _grid.CommitEdit(DataGridViewDataErrorContexts.Commit);
        }
    }

    private void GridOnCellEndEdit(object? sender, DataGridViewCellEventArgs e)
    {
        if (_isReloadingData)
            return;

        if (e.RowIndex < 0 || e.ColumnIndex < 0)
            return;

        if (_grid.Rows[e.RowIndex].DataBoundItem is not DataRowView rowView)
            return;

        var columnName = _grid.Columns[e.ColumnIndex].DataPropertyName;
        if (string.Equals(columnName, "name", StringComparison.OrdinalIgnoreCase))
            TryUpdateCodeFromName(rowView.Row);
        else if (string.Equals(columnName, "code", StringComparison.OrdinalIgnoreCase))
            _autoGeneratedCodeRows.Remove(rowView.Row);

        _grid.Refresh();
    }

    private void GridOnCellParsing(object? sender, DataGridViewCellParsingEventArgs e)
    {
        if (_isReloadingData || _table is null || e.RowIndex < 0 || e.ColumnIndex < 0)
            return;

        var columnName = _grid.Columns[e.ColumnIndex].DataPropertyName;
        if (string.IsNullOrWhiteSpace(columnName) || !_table.Columns.Contains(columnName))
            return;

        var column = _table.Columns[columnName];
        var targetType = Nullable.GetUnderlyingType(column.DataType) ?? column.DataType;
        if (targetType != typeof(decimal) &&
            targetType != typeof(double) &&
            targetType != typeof(float))
        {
            return;
        }

        var text = Convert.ToString(e.Value)?.Trim();
        if (string.IsNullOrWhiteSpace(text))
        {
            e.Value = column.AllowDBNull ? DBNull.Value : GetDefaultValue(column);
            e.ParsingApplied = true;
            return;
        }

        if (!TryParseFlexibleNumber(text, targetType, out var parsedValue))
            return;

        e.Value = parsedValue;
        e.ParsingApplied = true;
    }

    private void GridOnCellEnter(object? sender, DataGridViewCellEventArgs e)
    {
        if (_isReloadingData || e.RowIndex < 0 || e.ColumnIndex < 0)
            return;

        var columnName = _grid.Columns[e.ColumnIndex].DataPropertyName;
        if (!string.IsNullOrWhiteSpace(columnName))
            SelectFieldHelp(columnName);
    }

    private void GridOnColumnHeaderMouseClick(object? sender, DataGridViewCellMouseEventArgs e)
    {
        if (_isReloadingData || e.ColumnIndex < 0)
            return;

        var columnName = _grid.Columns[e.ColumnIndex].DataPropertyName;
        if (!string.IsNullOrWhiteSpace(columnName))
            SelectFieldHelp(columnName);
    }

    private void GridOnCellFormatting(object? sender, DataGridViewCellFormattingEventArgs e)
    {
        if (_isReloadingData || e.RowIndex < 0 || e.ColumnIndex < 0)
            return;

        if (_grid.Rows[e.RowIndex].DataBoundItem is not DataRowView rowView)
            return;

        var columnName = _grid.Columns[e.ColumnIndex].DataPropertyName;
        if (string.IsNullOrWhiteSpace(columnName))
            return;

        var rowTable = rowView.Row.Table;
        if (rowTable is null)
            return;

        if (!rowTable.Columns.Contains(columnName))
            return;

        if (rowTable.Columns[columnName] is not DataColumn column)
            return;

        if (TryGetValidationMessage(rowView.Row, column, out var message))
        {
            e.CellStyle ??= new DataGridViewCellStyle();
            e.CellStyle.BackColor = Color.MistyRose;
            e.CellStyle.SelectionBackColor = Color.IndianRed;
            e.CellStyle.SelectionForeColor = Color.White;
        }
    }

    private bool TryGetValidationMessage(DataRow row, DataColumn column, out string message)
    {
        message = string.Empty;
        if (row.RowState == DataRowState.Deleted)
            return false;

        if (IsMissingRequiredValue(row, column))
        {
            message = $"Cot '{column.ColumnName}' la bat buoc.";
            return true;
        }

        if (IsDuplicateValue(row, column))
        {
            message = $"Gia tri cua cot '{column.ColumnName}' dang bi trung theo rang buoc unique.";
            return true;
        }

        return false;
    }

    private bool IsDuplicateValue(DataRow row, DataColumn column)
    {
        var rowTable = row.Table;
        if (rowTable is null)
            return false;

        foreach (Constraint constraint in rowTable.Constraints)
        {
            if (constraint is not UniqueConstraint uniqueConstraint)
                continue;

            if (!uniqueConstraint.Columns.Any(x => x.ColumnName == column.ColumnName))
                continue;

            if (uniqueConstraint.Columns.Any(x => IsNullLike(row[x])))
                continue;

            var duplicates = rowTable.Rows
                .Cast<DataRow>()
                .Where(other => other.RowState != DataRowState.Deleted && !ReferenceEquals(other, row))
                .Where(other => uniqueConstraint.Columns.All(x => Equals(other[x], row[x])))
                .Any();

            if (duplicates)
                return true;
        }

        return false;
    }

    private void TryUpdateCodeFromName(DataRow row)
    {
        if (_table is null || !_table.Columns.Contains("name") || !_table.Columns.Contains("code"))
            return;

        var currentCode = Convert.ToString(row["code"]);
        if (!_autoGeneratedCodeRows.Contains(row) &&
            !string.IsNullOrWhiteSpace(currentCode))
        {
            return;
        }

        var name = Convert.ToString(row["name"]);
        if (string.IsNullOrWhiteSpace(name))
            return;

        var generatedCode = GenerateUniqueCodeFromName(name, row);
        row["code"] = generatedCode;
        _autoGeneratedCodeRows.Add(row);
    }

    private string GenerateUniqueCodeFromName(string name, DataRow currentRow)
    {
        var normalized = RemoveDiacritics(name.Trim()).ToLowerInvariant();
        var builder = new StringBuilder(normalized.Length);
        var previousWasSeparator = false;
        foreach (var character in normalized)
        {
            if (char.IsLetterOrDigit(character))
            {
                builder.Append(character);
                previousWasSeparator = false;
            }
            else if (!previousWasSeparator)
            {
                builder.Append('_');
                previousWasSeparator = true;
            }
        }

        var baseCode = builder.ToString().Trim('_');
        if (string.IsNullOrWhiteSpace(baseCode))
            baseCode = "new_code";

        if (_table is null)
            return baseCode;

        var existingCodes = _table.Rows
            .Cast<DataRow>()
            .Where(row => row.RowState != DataRowState.Deleted && !ReferenceEquals(row, currentRow))
            .Select(row => Convert.ToString(row["code"]))
            .Where(code => !string.IsNullOrWhiteSpace(code))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        if (!existingCodes.Contains(baseCode))
            return baseCode;

        var index = 1;
        while (existingCodes.Contains($"{baseCode}_{index}"))
            index++;

        return $"{baseCode}_{index}";
    }

    private static string RemoveDiacritics(string text)
    {
        var normalized = text.Normalize(NormalizationForm.FormD);
        var builder = new StringBuilder(normalized.Length);
        foreach (var character in normalized)
        {
            var unicodeCategory = CharUnicodeInfo.GetUnicodeCategory(character);
            if (unicodeCategory != UnicodeCategory.NonSpacingMark)
                builder.Append(character);
        }

        return builder.ToString().Normalize(NormalizationForm.FormC);
    }

    private void BuildGridColumns(AdminTableLoadRequest request, DataTable table)
    {
        _grid.AutoGenerateColumns = false;
        _grid.Columns.Clear();

        foreach (DataColumn column in table.Columns)
        {
            var binding = AdminColumnBindingCatalog.Find(request.Resource.TableName, column.ColumnName);
            DataGridViewColumn gridColumn;
            if (_lookupOptionsByColumn.TryGetValue(column.ColumnName, out var lookupOptions))
            {
                gridColumn = new DataGridViewComboBoxColumn
                {
                    DataPropertyName = column.ColumnName,
                    DataSource = lookupOptions.ToList(),
                    ValueMember = nameof(LookupOption.Value),
                    DisplayMember = nameof(LookupOption.Display),
                    DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton,
                    FlatStyle = FlatStyle.Popup
                };
            }
            else if (column.DataType == typeof(bool))
            {
                gridColumn = new DataGridViewCheckBoxColumn
                {
                    DataPropertyName = column.ColumnName
                };
            }
            else
            {
                gridColumn = new DataGridViewTextBoxColumn
                {
                    DataPropertyName = column.ColumnName
                };
            }

            gridColumn.Name = column.ColumnName;
            gridColumn.HeaderText = binding?.HeaderText ?? AdminColumnBindingCatalog.ToHeaderText(column.ColumnName);
            gridColumn.HeaderCell.ToolTipText = AdminFieldHelpCatalog.BuildHelpText(request.Resource, column, binding);
            gridColumn.ReadOnly = column.ReadOnly;
            _grid.Columns.Add(gridColumn);
        }
    }

    private void SelectFirstRow()
    {
        if (_grid.Rows.Count == 0 || _grid.Columns.Count == 0)
        {
            ClearGridSelection();
            return;
        }

        var firstVisibleRow = _grid.Rows
            .Cast<DataGridViewRow>()
            .FirstOrDefault(row => row.Visible && !row.IsNewRow && row.Cells.Count > 0);

        if (firstVisibleRow is null)
        {
            ClearGridSelection();
            return;
        }

        _grid.ClearSelection();
        firstVisibleRow.Selected = true;
        _grid.CurrentCell = firstVisibleRow.Cells[0];
    }

    private void SelectRow(DataRow row)
    {
        foreach (DataGridViewRow gridRow in _grid.Rows)
        {
            if (gridRow.DataBoundItem is not DataRowView rowView || !ReferenceEquals(rowView.Row, row))
                continue;

            _grid.ClearSelection();
            gridRow.Selected = true;
            if (gridRow.Cells.Count > 0)
                _grid.CurrentCell = gridRow.Cells[0];
            TryScrollRowIntoView(gridRow);
            return;
        }
    }

    private void ApplyFilter()
    {
        if (_table?.DefaultView is null)
            return;

        var keyword = _filterTextBox.Text.Trim().Replace("'", "''");
        if (string.IsNullOrWhiteSpace(keyword))
        {
            _table.DefaultView.RowFilter = string.Empty;
            EnsureGridSelectionMatchesView();
            _statusLabel.Text = _request is null
                ? "San sang."
                : $"Dang hien {_table.DefaultView.Count}/{_table.Rows.Count} dong cua {_request.Resource.TableName}.";
            return;
        }

        var filterParts = _table.Columns
            .Cast<DataColumn>()
            .Where(CanFilterColumn)
            .Select(column => $"Convert([{column.ColumnName}], 'System.String') LIKE '%{keyword}%'")
            .ToArray();

        if (filterParts.Length == 0)
        {
            _statusLabel.Text = "Bang nay khong co cot phu hop de loc nhanh.";
            return;
        }

        try
        {
            _table.DefaultView.RowFilter = string.Join(" OR ", filterParts);
            EnsureGridSelectionMatchesView();
            _statusLabel.Text = _request is null
                ? $"Dang hien {_table.DefaultView.Count}/{_table.Rows.Count} dong."
                : $"Dang hien {_table.DefaultView.Count}/{_table.Rows.Count} dong cua {_request.Resource.TableName}.";
        }
        catch (EvaluateException)
        {
            _table.DefaultView.RowFilter = string.Empty;
            EnsureGridSelectionMatchesView();
            _statusLabel.Text = "Khong the ap dung bo loc cho bang nay.";
        }
    }

    private void EnsureGridSelectionMatchesView()
    {
        if (_grid.Rows.Count == 0 || _grid.Columns.Count == 0)
        {
            ClearGridSelection();
            return;
        }

        if (_grid.CurrentRow is { Visible: true, IsNewRow: false } currentRow &&
            currentRow.DataBoundItem is DataRowView currentView &&
            ReferenceEquals(currentView.Row.Table, _table))
        {
            return;
        }

        SelectFirstRow();
    }

    private void ClearGridSelection()
    {
        _grid.ClearSelection();
        _grid.CurrentCell = null;
    }

    private void TryScrollRowIntoView(DataGridViewRow row)
    {
        if (row.IsNewRow || !row.Visible || row.Index < 0 || _grid.RowCount == 0)
            return;

        try
        {
            _grid.FirstDisplayedScrollingRowIndex = row.Index;
        }
        catch (InvalidOperationException)
        {
            // WinForms can throw when the grid is too small or not fully laid out yet.
            // Selection still succeeded, so we can safely ignore the scroll failure.
        }
    }

    private static bool CanFilterColumn(DataColumn column)
    {
        var type = column.DataType;
        return type == typeof(string)
            || type == typeof(short)
            || type == typeof(int)
            || type == typeof(long)
            || type == typeof(decimal)
            || type == typeof(double)
            || type == typeof(float)
            || type == typeof(bool)
            || type == typeof(DateTime)
            || type == typeof(Guid);
    }

    private static bool TryParseFlexibleNumber(string text, Type targetType, out object parsedValue)
    {
        parsedValue = default!;

        var normalized = text.Replace(" ", string.Empty);
        var styles = NumberStyles.AllowLeadingSign | NumberStyles.AllowDecimalPoint | NumberStyles.AllowThousands;
        var cultures = new[]
        {
            CultureInfo.CurrentCulture,
            CultureInfo.InvariantCulture,
            CultureInfo.GetCultureInfo("vi-VN"),
            CultureInfo.GetCultureInfo("en-US")
        };

        foreach (var culture in cultures.DistinctBy(static x => x.Name))
        {
            if (targetType == typeof(decimal) && decimal.TryParse(normalized, styles, culture, out var decimalValue))
            {
                parsedValue = decimalValue;
                return true;
            }

            if (targetType == typeof(double) && double.TryParse(normalized, styles, culture, out var doubleValue))
            {
                parsedValue = doubleValue;
                return true;
            }

            if (targetType == typeof(float) && float.TryParse(normalized, styles, culture, out var floatValue))
            {
                parsedValue = floatValue;
                return true;
            }
        }

        var alternate = normalized.Contains(',')
            ? normalized.Replace(",", ".")
            : normalized.Replace(".", ",");

        foreach (var culture in cultures.DistinctBy(static x => x.Name))
        {
            if (targetType == typeof(decimal) && decimal.TryParse(alternate, styles, culture, out var decimalValue))
            {
                parsedValue = decimalValue;
                return true;
            }

            if (targetType == typeof(double) && double.TryParse(alternate, styles, culture, out var doubleValue))
            {
                parsedValue = doubleValue;
                return true;
            }

            if (targetType == typeof(float) && float.TryParse(alternate, styles, culture, out var floatValue))
            {
                parsedValue = floatValue;
                return true;
            }
        }

        return false;
    }

    private sealed record ValidationIssue(
        DataRow Row,
        string ColumnName,
        string Message);

    private sealed record FieldHelpOption(
        string ColumnName,
        string DisplayName)
    {
        public override string ToString() => DisplayName;
    }
}
