using GameServer.Entities;

namespace GameServer.DTO;

public sealed record CharacterBaseStatsDto(
    Guid CharacterId,
    int? RealmTemplateId,
    string? RealmDisplayName,
    long? RealmMaxCultivation,
    double? BreakthroughChancePercent,
    bool? HasNextRealm,
    int? RealmLifespan,
    long? Cultivation,
    int? BaseHp,
    int? BaseMp,
    int? BaseAttack,
    int? BaseSpeed,
    int? BaseSpiritualSense,
    int? BaseStamina,
    int? LifespanBonus,
    double? BaseFortune,
    int? BasePotential,
    int? UnallocatedPotential,
    int? PotentialHpBonus,
    int? PotentialMpBonus,
    int? PotentialAttackBonus,
    int? PotentialSpeedBonus,
    int? PotentialSpiritualSenseBonus,
    double? PotentialFortuneBonus,
    decimal? CultivationProgress,
    int? FinalHp,
    int? FinalMp,
    int? FinalAttack,
    int? FinalSpeed,
    int? FinalSpiritualSense,
    int? FinalStamina,
    double? FinalFortune,
    int? HpUpgradeCount,
    int? MpUpgradeCount,
    int? AttackUpgradeCount,
    int? SpeedUpgradeCount,
    int? SpiritualSenseUpgradeCount,
    int? FortuneUpgradeCount,
    int? ActiveMartialArtId,
    bool? PotentialRewardLocked,
    IReadOnlyList<PotentialUpgradePreviewDto>? PotentialUpgradePreviews)
{
    public static CharacterBaseStatsDto FromEntity(CharacterBaseStat entity, int? realmLifespan = null) =>
        new(
            entity.CharacterId,
            entity.RealmId,
            null,
            null,
            null,
            null,
            realmLifespan,
            entity.Cultivation,
            entity.BaseHp,
            entity.BaseMp,
            entity.BaseAttack,
            entity.BaseSpeed,
            entity.BaseSpiritualSense,
            entity.BaseStamina,
            entity.LifespanBonus,
            entity.BaseFortune,
            entity.BasePotential,
            entity.UnallocatedPotential,
            0,
            0,
            0,
            0,
            0,
            0d,
            entity.CultivationProgress,
            entity.BaseHp,
            entity.BaseMp,
            entity.BaseAttack,
            entity.BaseSpeed,
            entity.BaseSpiritualSense,
            entity.BaseStamina,
            entity.BaseFortune,
            entity.HpUpgradeCount,
            entity.MpUpgradeCount,
            entity.AttackUpgradeCount,
            entity.SpeedUpgradeCount,
            entity.SpiritualSenseUpgradeCount,
            entity.FortuneUpgradeCount,
            entity.ActiveMartialArtId,
            entity.PotentialRewardLocked,
            null);
}
