using GameServer.Entities;

namespace GameServer.DTO;

public sealed record CharacterBaseStatsDto(
    Guid CharacterId,
    int? RealmTemplateId,
    string? RealmDisplayName,
    long? RealmMaxCultivation,
    double? BreakthroughChancePercent,
    bool? HasNextRealm,
    int? RealmLifespan,
    long? Cultivation,
    int? BaseHp,
    int? BaseMp,
    int? BaseAttack,
    float? BaseMoveSpeed,
    int? BaseSpeed,
    int? BaseSense,
    int? BaseStamina,
    int? LifespanBonus,
    double? BaseLuck,
    int? BasePotential,
    int? UnallocatedPotential,
    int? PotentialHpBonus,
    int? PotentialMpBonus,
    int? PotentialAttackBonus,
    int? PotentialSpeedBonus,
    int? PotentialSenseBonus,
    double? PotentialLuckBonus,
    decimal? CultivationProgress,
    int? FinalHp,
    int? FinalMp,
    int? FinalAttack,
    int? FinalSpeed,
    int? FinalSense,
    int? FinalStamina,
    double? FinalLuck,
    int? HpUpgradeCount,
    int? MpUpgradeCount,
    int? AttackUpgradeCount,
    int? SpeedUpgradeCount,
    int? SenseUpgradeCount,
    int? LuckUpgradeCount,
    int? ActiveMartialArtId,
    bool? PotentialRewardLocked,
    IReadOnlyList<PotentialUpgradePreviewDto>? PotentialUpgradePreviews)
{
    public static CharacterBaseStatsDto FromEntity(CharacterBaseStat entity, int? realmLifespan = null) =>
        new(
            entity.CharacterId,
            entity.RealmId,
            null,
            null,
            null,
            null,
            realmLifespan,
            entity.Cultivation,
            entity.BaseHp,
            entity.BaseMp,
            entity.BaseAttack,
            entity.BaseMoveSpeed.HasValue ? (float)entity.BaseMoveSpeed.Value : null,
            entity.BaseSpeed,
            entity.BaseSense,
            entity.BaseStamina,
            entity.LifespanBonus,
            entity.BaseLuck,
            entity.BasePotential,
            entity.UnallocatedPotential,
            0,
            0,
            0,
            0,
            0,
            0d,
            entity.CultivationProgress,
            entity.BaseHp,
            entity.BaseMp,
            entity.BaseAttack,
            entity.BaseSpeed,
            entity.BaseSense,
            entity.BaseStamina,
            entity.BaseLuck,
            entity.HpUpgradeCount,
            entity.MpUpgradeCount,
            entity.AttackUpgradeCount,
            entity.SpeedUpgradeCount,
            entity.SenseUpgradeCount,
            entity.LuckUpgradeCount,
            entity.ActiveMartialArtId,
            entity.PotentialRewardLocked,
            null);
}
